feat: 셀럽의 새로운 유튜브 영상 데이터 조회 api 구현
woowacourse-teams/2023-celuveat pull request #102
Opened 2023-07-12 11:17 UTC by kdkdhoho

## ✨ 요약
1. 테이블에 저장된 유튜브 영상 이력(VideoHistory)를 모두 조회해오는 API를 구현했어. 관리자 페이지에서 사용할 기능이야
2. AcceptanceTest를 상속받는 모든 클래스에 `@SuppressWarnings(“NonAsciiCharacter”)`가 중복으로 있어서 제거했어.
3. 추가로 `/videos/history` url 괜찮은지 잘 모르겠네,, 리뷰 남겨줘!!

<br>

## 😎 해결한 이슈
- close #20

2023-07-12 11:34 UTC, shin-mallang requested changes
지금 이런 말 하긴 너무 미안한데, 영상 이력같은 경우는 admin에서만 쓰니까 admin 패키지에 들어있는게 오히려 나을 수도 있다 생각하는데, 어떻게 생각해.,.?

2023-07-12 11:34 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/celuveat/video/application/dto/FindAllVideoHistoryResponse.java
> +        boolean ads
isAds로 반환해줘!
JsonProperty같은거 찾아보면 될거야

2023-07-12 11:34 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/celuveat/video/presentation/VideoHistoryController.java
> +@RequestMapping("/videos/history")
video의 history의 느낌이라기보단 videohistory가 하나의 도메인으로 생각되어서 
나는 `/videohistories` 로 하는 게 좋아보여
다른 사람들 의견도 궁금하네

추가로 어드민에서만 쓰느거니까 /admin 붙여주는것도 좋은 것 같아..?

2023-07-12 11:34 UTC, shin-mallang commented on backend/src/test/java/com/celuveat/celuveat/video/application/VideoHistoryQueryServiceTest.java
> +        var result = videoHistoryQueryService.findAllVideoHistoryResponses();
인수 테스트 아니면 var 을 지금까지 안 쓰긴 했는데, 어떻게 생각해

2023-07-12 11:40 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/celuveat/video/application/dto/FindAllVideoHistoryResponse.java
> +        boolean ads
이 부분은 내일 만나서 물어볼게

2023-07-12 11:41 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/celuveat/video/presentation/VideoHistoryController.java
> +@RequestMapping("/videos/history")
말랑 의견 적합한 것 같아!
나도 다른 사람들 의견 궁금해서 일단 둘게~

2023-07-12 11:47 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/celuveat/video/application/VideoHistoryQueryServiceTest.java
> +        var result = videoHistoryQueryService.findAllVideoHistoryResponses();
사실 인수테스트 아닐 때도 안쓰는 이유를 잘 모르겠어.
이번에 인수 테스트에서 var로 통일하는 김에 단위 테스트에서도 var로 통일해봤는데 별로야? 테스트에서는 자유롭게 쓰는건 어때??

2023-07-12 12:54 UTC, shin-mallang commented on backend/src/test/java/com/celuveat/celuveat/video/application/VideoHistoryQueryServiceTest.java
> +        var result = videoHistoryQueryService.findAllVideoHistoryResponses();
나는 다음과 같은 목적을 두고 테스트를 작성해.

인수테스트의 경우 개발자가 아닌 사람이 보아도 이해할 수 있도록 작성하는게 목표라서, 반환 타입이 무엇인지등에 대한 정보는 중요하지 않다고 봐.
그래서 var을 사용하는거고.

그런데 인수테스트가 아닌 경우, 이는 이후 테스트의 유지보수와, 개발자인 사람이 테스트를 보고 한번에 파악하기 쉬워야 한다고 생각해.
(어떤 타입이 필요하고, 어떤 타입이 필요하는지 등에 대한 정보는 모두 개발자한테 유용한 정보라 생각해)
그래서 나는 인수테스트가 아니라면 var을 사용하는 것을 좋아하지 않아.
예시로 PR을 리뷰할 때에도, 깃허브에서만 코드를 보면 어떤 타입이 필요하고 반환되는지를 알 수 없어서 조금 혼동돼!

2023-07-12 15:10 UTC, odo27 approved these changes
도기 넘넘 고생 많았어! 👍

2023-07-12 15:10 UTC, odo27 commented on backend/src/test/java/com/celuveat/celuveat/video/infra/persistence/FakeVideoHistoryQueryDao.java
> +    private final Map<Long, VideoHistory> store = new LinkedHashMap<>();
LinkedHashMap 을 사용한 이유가 있을까?

2023-07-12 23:54 UTC, TaeyeonRoyce approved these changes
도기, 완전 잘 작성했네! 고생 많았어~!
다른 크루들 리뷰에 대한 내 의견만 좀 남겨두었는데 같이 고민해보자!

2023-07-12 23:54 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/celuveat/video/application/VideoHistoryQueryServiceTest.java
> +        var result = videoHistoryQueryService.findAllVideoHistoryResponses();
나도 의견을 좀 남기자면
var은 안쓰는게 좋다고 생각해.
반환 타입으로도 많은 정보를 얻을 수 있잖아.

나는 개인적으로 인수테스트에서도 안쓰면 좋다고 생각하지만,
RestAssured의 반환 타입의 길이도 길고, 우리 도메인과 관계없는 불필요한 타입들이 반환되어서 `var`를 쓰는게 더 효율적이라 생각했어

2023-07-12 23:54 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/celuveat/video/presentation/VideoHistoryController.java
> +@RequestMapping("/videos/history")
말랑이 추가한 interceptor도 고려하면 
`/admin/videohistories` 가 좋아보여!

2023-07-13 00:58 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/celuveat/video/application/VideoHistoryQueryServiceTest.java
> +        var result = videoHistoryQueryService.findAllVideoHistoryResponses();
두 의견 모두 납득돼서 수정하도록 할게!

2023-07-13 01:53 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/celuveat/video/infra/persistence/FakeVideoHistoryQueryDao.java
> +    private final Map<Long, VideoHistory> store = new LinkedHashMap<>();
영상 이력은 저장된 순서로 가져오는 게 중요하다고 생각해서 사용했어.

2023-07-13 01:58 UTC, shin-mallang approved these changes
고생했어!!

2023-07-13 01:58 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/celuveat/admin/presentation/VideoHistoryController.java
> +public class VideoHistoryController {
`AdminVideoHistoryController` !!

2023-07-13 02:17 UTC, merged