feat: 로딩 컴포넌트 구현
woowacourse-teams/2023-celuveat pull request #140
Opened 2023-07-19 07:16 UTC by D0Dam

## ✨ 요약

로딩 컴포넌트를 구현했습니다.
size 를 전달하면 그 szie에 맞는 크기의 로딩 애니매이션을 볼 수 있습니다.

![loadingAnimation](https://github.com/woowacourse-teams/2023-celuveat/assets/51052049/ee71e273-5dca-4e63-a3d5-4cfb4cfa18a1)

<br><br>

## 😎 해결한 이슈
- 아직이에요

<br><br>

2023-07-24 03:21 UTC, turtle601 requested changes
1. LoadingCeluveat vs LoadingDot 컴포넌트 
- 스토리북으로 두 개의 컴포넌트를 둘 다 확인했습니다. 너무나 이쁘네요!!
- 하지만 두 개의 컴포넌트의 쓰임새가 저희 프로젝트 내에서는 거의 똑같을 거 같아서 두 개 중 하나만 구현해도 괜찮을 거 같습니다. 
(Loading prefix를 붙이다 보니 (ex. LoadingCeluveat, LoadingDots) 해당 컴포넌트의 쓰임새를 명확히 알 수가 없었어요..) 

2. 폴더 구조 분리
- Loading 폴더를 역할의 기준에 따라 묶으셨군요!! 너무 좋습니다. 하지만 처음 코드를 볼때 Loading이라는 컴포넌트를 만들기 위한 부속 컴포넌트를 만든건가?? 라는 의문이 들었습니다. (제가 그렇게 해서...)
- 따라서 각각 재사용 가능한 컴포넌트라는 것을 나타내기 위해 LoadingDots, Skeleton 등도 폴더로 묶어 놓았으면 좋겠습니다. 

3. 애니메이션 common 분리
- 어떤 애니메이션은 common으로 분리, 어떤 애니메이션은 common으로 분리하지 않았는데 그 이유가 어떤 건지 궁금합니다. 
- 애니메이션이라는 파일을 따로 만들어도 좋을거 같네요.

2023-07-24 08:07 UTC, D0Dam commented
> 1. LoadingCeluveat vs LoadingDot 컴포넌트
> 
> * 스토리북으로 두 개의 컴포넌트를 둘 다 확인했습니다. 너무나 이쁘네요!!
> * 하지만 두 개의 컴포넌트의 쓰임새가 저희 프로젝트 내에서는 거의 똑같을 거 같아서 두 개 중 하나만 구현해도 괜찮을 거 같습니다.
>   (Loading prefix를 붙이다 보니 (ex. LoadingCeluveat, LoadingDots) 해당 컴포넌트의 쓰임새를 명확히 알 수가 없었어요..)

음.. 제가 생각했을 때는 `Loading` 이라는 의미가 담겨 있으니 `Loading` 을 할 때 사용한다는 쓰임새를 나타낼 수 있다고 생각해요. 물론 어떤 Loading 상태에서 어떤 Loading 모션을 보여줄 지를 예측할수는 없지만, LoadingSpinner와 같은 네이밍도 명확하게 특정 상태에서 사용한다고 단정짓는 네이밍은 아니니까요!

그렇다면 푸만능은 해당 네이밍이 어떤 식이었으면 좋은 것 같나요? 한 번 네이밍을 들어보면 설득 요소가 될 것 같아요!

> 2. 폴더 구조 분리
> 
> * Loading 폴더를 역할의 기준에 따라 묶으셨군요!! 너무 좋습니다. 하지만 처음 코드를 볼때 Loading이라는 컴포넌트를 만들기 위한 부속 컴포넌트를 만든건가?? 라는 의문이 들었습니다. (제가 그렇게 해서...)
> * 따라서 각각 재사용 가능한 컴포넌트라는 것을 나타내기 위해 LoadingDots, Skeleton 등도 폴더로 묶어 놓았으면 좋겠습니다.

이 부분은 어느정도 동의해요. 다른 곳에서도 폴더의 쓰임이 푸만능이 말한 것처럼 되어 있네요! 수정해볼게요~!

> 3. 애니메이션 common 분리
> 
> * 어떤 애니메이션은 common으로 분리, 어떤 애니메이션은 common으로 분리하지 않았는데 그 이유가 어떤 건지 궁금합니다.
> * 애니메이션이라는 파일을 따로 만들어도 좋을거 같네요.

commom에 분리된 에니메이션(keyframe)은 common 에 정의되는 css 함수에 종속됩니다. 그 keyframe도 같이 함수안에 정의하고 싶었는데... 그게 안되어서 빼 놓았어요!

2023-07-25 02:39 UTC, D0Dam commented
같이 상의한 내용 반영했습니다~!

2023-07-26 02:02 UTC, shackstack approved these changes

2023-07-26 02:02 UTC, turtle601 approved these changes

2023-07-26 02:03 UTC, merged