feat: 소셜 로그인 구현
woowacourse-teams/2023-celuveat pull request #173
Opened 2023-07-25 07:44 UTC by odo27

## ✨ 요약
```
- KakaoOAuthClient 구현
- 카카오 아이디로 회원을 조회하고 없으면 회원가입하도록 구현
```

<br><br>

## 😎 해결한 이슈
- close #158 

<br><br>

2023-07-25 14:44 UTC, TaeyeonRoyce requested changes
오도 외부 api 연동하느라 고생많았어~!
전반적으로 임시 코드가 많아보이는데 우선 코드 기준으로 리뷰 남겨두었어!
리뷰 읽고 공감하는 부분들은 반영해줘!

2023-07-25 14:44 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/auth/infra/kakao/dto/TokenResponse.java
> +        String scope
API요청의 Response 바인딩을 위해 `snake_case`를 사용한 것 같은데
application 영역에서도 저런 이름으로 돌아다니는건 별론거 같어.

ex. 
getter의 경우`tokenResponse.token_type()`

필드이름은 카멜케이스로 가고
`@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)`
사용해서 바인딩 되도록 하자

2023-07-25 14:44 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/auth/presentation/OAuthLoginController.java
> +        response.sendRedirect("http://localhost:3000");
redirect url 도 profile에서 관리하자!

2023-07-25 14:44 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/member/domain/Member.java
> +    private Long oAuthId;
단일단어로 시작하는 변수명은 피하면 좋을 것 같아!

2023-07-25 14:44 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/auth/presentation/OAuthLoginController.java
> +        authService.login(code, kakaoOAuthClient);
`login`에서 회원가입이랑 기존 회원 로그인 로직이 동시에 이루어지고 있는데, 분리해서 응답할 필요가 있을 것 같아

2023-07-26 07:24 UTC, shin-mallang approved these changes

2023-07-26 07:26 UTC, TaeyeonRoyce approved these changes

2023-07-26 07:26 UTC, merged