feat: 레스토랑 카드 및 마커 클릭 이벤트 변경
woowacourse-teams/2023-celuveat pull request #198
Opened 2023-07-28 07:59 UTC by shackstack

## ✨ 요약
```
레스토랑 카드 및 마커 클릭 이벤트 변경
```

<br><br>

## 😎 해결한 이슈
- close #192 

<br><br>

2023-07-28 12:36 UTC, turtle601 reviewed
Map에 어려운 로직들이 많은데 이렇게 빨리 잘 해주셨네요~~ 폼 미쳣다..

2023-07-28 12:36 UTC, turtle601 commented on frontend/src/components/@common/Map/Map.tsx
> +  const [mainPosition, setMainPosition] = useState({ lat: 37.5057482, lng: 127.050727 });
state 초기값이 무엇을 나타내는지 네이밍을 지으면 좋겠어요

```tsx
const [mainPosition, setMainPosition] = useState(잠실캠 위도경도);

```

2023-07-28 12:36 UTC, turtle601 commented on frontend/src/components/@common/Map/OverlayMarker.tsx
> +  quadrant: Quadrant;
quadrant가 사분면을 뜻하는 군요 ㅋㅋㅋㅋ

2023-07-28 12:36 UTC, turtle601 commented on frontend/src/hooks/useOnClickOuside.ts
> +import { useEffect, RefObject } from 'react';
네이밍과 전체적인 로직을 보았을 때 blur이벤트와 유사한 점이 많아 보입니다. 해당 훅을 만든 이유에 대해 궁금해요!!

2023-07-28 12:36 UTC, turtle601 commented on frontend/src/pages/MainPage.tsx
> +              <RestaurantCard restaurant={restaurant} celebs={celebs} size={42} onClick={() => {}} />
RestaurantCard의 onClick이벤트 머선일이고...

당장은 onClick 이벤트를 넣고 싶지 않다면 옵셔널로 하거나 컴포넌트 props 구조를 수정하는 방향으로 가면 좋을 거 같아요

2023-07-28 12:36 UTC, turtle601 commented on frontend/src/utils/getQuadrant.ts
> +  return 1;
`return 1`이 겹치네용~ 코드를 축약할 수 있을 거 같아요!!

2023-07-28 12:36 UTC, turtle601 commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +        src={`http://3.35.157.27:3000/images-data/${images[0].name}`}
URL 변수는 .env 파일로 숨기는 것이 좋아보여용!!

저는 이번에 url 변수를 .env 파일에 넣고 
```ts
const BASE_URL = `${window.location.protocal}//${process.env.BASE_URL}`

```

이런 형식으로 쓰고 있답니다 (현재 진행중...)

2023-07-28 12:36 UTC, turtle601 commented on frontend/src/components/@common/ProfileImage/ProfileImage.tsx
> +  width: ${({ size }) => (size ? `${size}px` : '100%')};
이럴거면 string으로 받는게 낫지 않을까... 라는 생각 ㅎㅎ

2023-07-28 12:36 UTC, turtle601 commented on frontend/src/components/@common/Map/OverlayMarker.tsx
> +const fadeInAnimation = keyframes`
요 애니메이션은 많이 쓰일거 같네용 ~~ 공통 css로 빼도 좋을 거 같아여!!

2023-07-29 02:46 UTC, D0Dam requested changes
불필요한 로직이 많이 삭제 되었네요! 공용 훅이나 유틸도 잘 구현한 것 같아요!
몇몇가지 변경 사항과 코멘트만 읽고 반영 부탁드립니다! 수고하셨어요~~!

2023-07-29 02:46 UTC, D0Dam commented on frontend/src/components/@common/Map/OverlayMarker.tsx
> +        <StyledMarker onClick={() => setIsClicked(true)} isClicked={isClicked} ref={ref}>
`StyledMarker` 안에 있는 onClick에 들어간 함수를 외부로 분리하면 좋을 것 같아요!

```suggestion
         const clickMarker = () => setIsClicked(true);
...
        <StyledMarker onClick={clickMarker} isClicked={isClicked} ref={ref}>
```

2023-07-29 02:46 UTC, D0Dam commented on frontend/src/components/@common/Map/OverlayMarker.tsx
> +            <RestaurantCard restaurant={restaurant} onClick={() => {}} type="map" />
onClick 은 지워주어도 좋을 것 같아요!
```suggestion
            <RestaurantCard restaurant={restaurant} type="map" />
```

2023-07-29 02:46 UTC, D0Dam commented on frontend/src/hooks/useOnClickOuside.ts
> +import { useEffect, RefObject } from 'react';
지나가는 길에 살짝 첨언 하자면...
blur 이벤트는 focus 이벤트가 존재해야 blur 이벤트를 동작시킬 수 있습니다.
blur 이벤트를 동작시킬 수 없는 `div` 태그와 같은 경우에는 blur 역할을 하는 훅을 사용하기도 한답니다.

물론 강제로 tabIndex={0} 과 같은 방법으로 focus 를 줄 수도 있겠지만
애초에 목적 자체가 요소가 focus 되고 blur 되는 로직이 아닌, 요소가 click 되고 밖의 요소가 click 이되는 로직에 사용하는 훅이라고 생각해요~! (focus ≠ onClick , onblur ≠ clickOutside)

2023-07-30 07:28 UTC, shackstack reviewed
피드백 감사합니다. 반영해서 수정하였습니다.

2023-07-31 01:22 UTC, D0Dam commented on frontend/src/components/@common/ProfileImage/ProfileImage.tsx
> +  width: ${({ size }) => (size ? `${size}px` : '100%')};
저도 굳이 px 이외의 값을 고려할 필요가 없다고 느껴 이렇게 만들었는데, 이제는 그냥 string 으로 줄 필요가 있겠네요! string 으로 바꾸는 쪽으로 가죠!

2023-07-31 01:40 UTC, D0Dam requested changes
hover 까지 잘 추가해 주셨네요! hover 의 상태를 관리하는 로직에서 제 의견을 첨언 해 보았어요!
관련해서 추가 의견이나 궁금사항이 있으면 오늘 미팅 때 같이 이야기 해  보아요~!

2023-07-31 01:40 UTC, D0Dam commented on frontend/src/components/@common/Map/OverlayMarker.tsx
> +          </StyledModal>
이 두개를 하나의 요소로 묶어주는 작업이 필요할 것 같아요! 버그 목록으로 공유했지만, 이 경우에는 음식점 카드를 누르면 음식점 카드가 그대로 꺼져버리거든요..! 이 부분은 같이 만나서 작업하는 걸로 할까요?

2023-07-31 01:40 UTC, D0Dam commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +    <StyledContainer onClick={onClick} onMouseEnter={() => onMouseEnter(restaurant.id)} onMouseLeave={onMouseLeave}>
onMouseEnter 안의 함수도 밖으로 분리해 주실 수 있을까요?

```suggestion
    <StyledContainer onClick={onClick} onMouseEnter={onMouseEnter} onMouseLeave={onMouseLeave}>
```

2023-07-31 01:40 UTC, D0Dam commented on frontend/src/pages/MainPage.tsx
> +  const [isHoveredList, setIsHoveredList] = useState<{ cardId: number; isHovered: boolean }[]>([]);
제 생각이지만... 상태를 이렇게 두지 않고 그냥 hover 된 cardId 를 넘기는 식으로 하면 로직이 더 간단해 질 것 같은데요?
네이밍이 이건 호버된 리스트니? 의 형식인것도 살짝 어색한 것 같아요..!
고친다면 아래와 같이 고칠 것 같아요!

```suggestion
  const [hoveredCardId, setHoveredCardId] = useState<number | null>(null);
```

그럼 fetch 함수 안에서의 set 로직이 사라지게 될 것 같아요!
```
      const newIsHoveredList = content?.map(restaurant => ({ cardId: restaurant.id, isHovered: false }));
      setIsHoveredList(newIsHoveredList);
```

2023-07-31 01:40 UTC, D0Dam commented on frontend/src/pages/MainPage.tsx
> +  };
위의 코멘트에 이어서... 그럼 이 함수들도 다음과 같이 표현할 수 있겠죠?

```suggestion
  const hoverRestaurantCard = (targetId: number) => setIsHoveredList(targetId);

  const unHoverRestaurantCard = () => setIsHoveredList(null);
```

2023-07-31 04:12 UTC, shackstack commented on frontend/src/pages/MainPage.tsx
> +  const [isHoveredList, setIsHoveredList] = useState<{ cardId: number; isHovered: boolean }[]>([]);
좋습니다! 확실히 더 좋은 로직인 것 같아요 👍

2023-07-31 04:12 UTC, shackstack commented on frontend/src/components/@common/ProfileImage/ProfileImage.tsx
> +  width: ${({ size }) => (size ? `${size}px` : '100%')};
반영했습니다.

2023-07-31 05:41 UTC, D0Dam approved these changes
approve 하겠습니다~! 수고하셨어요~!

2023-07-31 05:41 UTC, turtle601 approved these changes

2023-07-31 05:41 UTC, merged