feat: 지역 검색 기능
woowacourse-teams/2023-celuveat pull request #285
Opened 2023-08-08 08:36 UTC by shackstack

## ✨ 요약
```
지역 검색 기능 
```

<br><br>

## 😎 해결한 이슈
- close #272 

<br><br>

<img width="458" alt="스크린샷 2023-08-08 오후 5 36 36" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/524e420c-8e65-4076-b37d-1fecf7305cd3">

2023-08-08 11:45 UTC, D0Dam requested changes
검색창 수고하셨어요~! 아직 추가되지 않은 디자인 커스텀과 더불어 아래에 적어놓은 소소한 변경사항만 반영해주시면 될 것 같아요~! 수고하셨습니다~!

2023-08-08 11:45 UTC, D0Dam commented on frontend/src/components/@common/Header/Header.tsx
> +};
로딩 중일 때 스타일이 안맞아요~! 지도랑은 다른 ui 를 적용해야 할 것 같아요~!

2023-08-08 11:45 UTC, D0Dam commented on frontend/src/components/SearchBar/SearchBar.tsx
> +  box-shadow: 0 4px 12px 0 rgb(0 0 0 / 5%), 0 1px 2px 0 rgb(0 0 0 / 8%);
기존에 있는 box-shadow 옵션을 써 주면 좋을 것 같아요~!

2023-08-08 11:45 UTC, D0Dam commented on frontend/src/components/SearchBar/SearchBar.tsx
> +  font-size: medium;
기존에 있는 font-size 옵션을 사용해 주면 더 좋을 것 같아요~!

2023-08-08 11:45 UTC, D0Dam commented on frontend/src/components/SearchBar/SearchBar.tsx
> +  background-color: var(--red-2);
셀럽잇의 색깔에 맞게 primary 색상 계열로 가는 것이 어떨까요?

2023-08-08 11:45 UTC, D0Dam commented on frontend/src/hooks/store/useMapState.ts
> +export default useMapState;
개인적으로 boundary 쪽은 queryParams 로 쓰여서 그쪽끼리 묶고 싶은데 말이죠...
일단 차후에 논의해봐야 될 부분 같아서 한 번 참고만 해주세요~!

2023-08-08 23:50 UTC, turtle601 commented
검색창 엔터키를 누르거나 돋보기 버튼을 클릭했을 때 어떠한 동작도 하지 않더라구요...

해당 기능도 추가적으로 구현하면 좋을 것 같아요!!

2023-08-09 00:09 UTC, shackstack commented on frontend/src/components/SearchBar/SearchBar.tsx
> +  background-color: var(--red-2);
primary 색상 적용해봤더니 별로더라구요 같이 있을때 상의 해봅시다.

2023-08-09 02:33 UTC, D0Dam approved these changes
잘 수정해 주셨네요~! 디자인  머싯네요! 고생하셨습니다~!

2023-08-10 10:32 UTC, turtle601 approved these changes
도담이 전반적으로 잘 이야기 해줘서 저는 리뷰할 게 크게 없는 것 같아요!!
기능 구현도 급하니 일단 approve하도록 하겠습니다!!

근디 검색창 엔터 시 동작은 아직 구현 안하신 건가요..?? 아직 동작을 안하네용...

2023-08-11 02:54 UTC, merged