feat: 주변 음식점 조회 api 구현
woowacourse-teams/2023-celuveat pull request #292
Opened 2023-08-09 05:58 UTC by kdkdhoho

## ✨ 요약
1. 특정 음식점의 ID와 Optional한 값의 distance(단위: m)를 받아, 해당 음식점 주변의 모든 음식점을 조회하는 기능입니다.
2. distance는 쿼리  파라미터로 요청되며, 값이 입력되지 않으면 default 3km로 설정했습니다.
3. 페이징으로 구현했으며, 한 페이지의 사이즈는 4입니다.
4. 음식점들을 거리순으로 정렬하여 반환합니다.

<br>

## 😎 해결한 이슈
- close #280  

<br>

2023-08-09 08:03 UTC, shin-mallang requested changes
오우 너무 좋은데요~?

2023-08-09 15:32 UTC, TaeyeonRoyce approved these changes
도기 테스트도 꼼꼼하고 좋아요~!
말랑 피드백 반영하면 좋을 것 같아!

테스트쪽에 간단한 코멘트 남겼어!

2023-08-09 15:32 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/restaurant/application/RestaurantQueryServiceTest.java
> +                .doesNotContain(restaurant.name());
ditto

2023-08-09 15:32 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/restaurant/domain/RestaurantQueryRepositoryTest.java
> +                .doesNotContain(restaurant.name());
여기도!

2023-08-10 01:55 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
> +            WHERE %s <= %d AND id != %d
<img width="1122" alt="image" src="https://github.com/woowacourse-teams/2023-celuveat/assets/66300965/c0f1ad98-3924-4ba3-a45f-f3f4d7c186e4">

WHERE 절에 dist가 들어가면 쿼리 실행순서 때문에 위 같은 에러가 발생하는 것 같은데, 다른 방법이 있을까??

2023-08-10 02:16 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
> +    public Page<RestaurantWithDistance> getRestaurantsWithDistanceNearBy(
좋은 의견 고마워!
안그래도 2번 방법에 대해선 처음엔 서비스에서 시도해봤는데, unmodifiableList로 반환함과 동시에 setContent가 없어서 레포지토리로 내렸어.
그런데 새로운 Page 객체를 생성하는 방법이 생각나서 그렇게 해결해보려고. 고마워 !!

2023-08-10 02:26 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java
> +                .allMatch(distance -> distance <= 요청_거리);
이렇게도 되는구나! 고마워요 👍

2023-08-10 04:22 UTC, odo27 approved these changes
도형 테스트 꼼꼼히 잘 짰네!! 👍

2023-08-10 04:22 UTC, odo27 commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java
> +    public static void 특정_거리_이내에_있는_음식점이며_기준이_되는_음식점은_포함하지_않는지_검증한다(
너무 좋은데요 👍👍

2023-08-10 05:44 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
> +            WHERE %s <= %d AND id != %d
마땅한 방법이 안 떠오르네.. ㅠㅠ
일단 이렇게 가자!

2023-08-10 05:51 UTC, shin-mallang approved these changes
굳굳 사소한거 하나만 더 남겼어!

2023-08-10 05:51 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +        return PageableExecutionUtils.getPage(newContent, pageable, restaurantsWithDistance::getTotalElements);
이거 맨 위에 보면 new PageImpl()로 해둔 게 있어서, 그거랑 맞춰주면 좋을 것 같아!

2023-08-10 05:52 UTC, shin-mallang requested changes
미안미안 하나 더!

2023-08-10 05:52 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +    public Page<RestaurantQueryResponse> findAllNearByDistance(
이거 메서드 이름에서 특정 음식점을 제거한다는게 여전히 안들어가있어!

2023-08-11 01:03 UTC, merged