feat: 음식점 조회시 좋아요 조회수 포함 반환 기능 구현
woowacourse-teams/2023-celuveat pull request #306
Opened 2023-08-10 09:35 UTC by odo27

## ✨ 요약
```
음식점 전체 조회시 회원의 좋아요 여부와 조회수를 포함해 반환하는 기능을 구현했습니다.
로그인되어 있지 않으면 좋아요 여부는 무조건 false로 반환됩니다.
음식점 전체 조회시 셀럽 필터가 포함되어 있다면 celebs 배열과 images 배열을 정렬합니다.
```

<br><br>

## 😎 해결한 이슈
- close #271 

<br><br>

2023-08-10 10:43 UTC, kdkdhoho reviewed
오동~ 엄청 복잡했을텐데 고생 많았어 👍
코멘트 확인해줘!

2023-08-10 10:43 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +        List<Object[]> results = restaurantLikeRepository.countLikesByRestaurantIds(restaurantIds);
`results`라는 이름말고 더 명확한 이름 없을까? 🧐

2023-08-10 10:43 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +        System.out.println(restaurantIds);
제거해주세욤

2023-08-10 10:43 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +        return likeCountByRestaurantId;
```suggestion
return restaurantIds.stream()
                .collect(toMap(
                        identity(),
                        id -> 0
                ));
```
이렇게 해도 될 것 같아

2023-08-10 10:43 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +    private Map<Long, Integer> groupingLikeCountByRestaurant(List<Object[]> results, List<Long> restaurantIds) {
`results`라는 이름말고 더 명확한 이름 없을까? 🧐

2023-08-10 10:43 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +            Integer likeCount = ((Number) result[1]).intValue();
매직넘버..!

2023-08-10 10:43 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +    private Map<Long, Integer> initializeLikeCount(List<Long> restaurantIds) {
근데 이거 안해줘도 쿼리문에서 0으로 나오지 않나?? (진짜 모름)

2023-08-10 10:43 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +        Map<Long, Integer> likeCounts = groupingLikeCountByRestaurant(results, restaurantIds);
인텔리제이에서 이 부분 코드 중복이라고 뜨네.
PR 수정하면서 중복 제거도 하면 좋을 것 같아!

2023-08-10 10:43 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryFacade.java
> +        );
```suggestion
        Page<RestaurantQueryResponse> aa = memberId.map(id -> restaurantQueryService.findAllWithMemberId(
                        restaurantSearchCond,
                        locationSearchCond,
                        pageable,
                        id))
                .orElse(restaurantQueryService.findAll(restaurantSearchCond, locationSearchCond, pageable));
```
이렇게 `map`이랑 `orElse`를 섞어서 쓸 수 있더라고.
혹시 이거때문에 `CustomeOptional`을 만들었을까??

2023-08-10 10:43 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java
> +        void 음식점_전체_조회시_좋아요와_조회수를_함께_반환한다() {
복잡한 테스트 고생했어 🥲

2023-08-11 00:06 UTC, shin-mallang requested changes
이따 만나서 같이 조금씩 수정해보자!

2023-08-11 00:06 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +        Map<Long, Integer> likeCounts = groupingLikeCountByRestaurant(results, restaurantIds);
코드가 대체로 중복인게 많아서, findAll + Facade에서 추가 작업을 진행해도 좋아보여!

2023-08-11 00:33 UTC, TaeyeonRoyce requested changes
오도 고생 많았어.
코멘트 보고 리뷰 반영해줘!

2023-08-11 00:33 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +    private Map<Long, Integer> initializeLikeCount(List<Long> restaurantIds) {
이 메서드도 필요 없을 것 같아.
```java
Map<Long, Integer> likeCountByRestaurantId = restaurantIds.stream()
                .collect(Collectors.toMap(Function.identity(), likeCount -> 0));
```
로 대체해도 되고

2023-08-11 00:33 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/application/dto/RestaurantQueryResponse.java
> +                false,
이 부분도 개선할 수 있을 것 같아.
아래 `isLiked`를 파라미터로 받는 생성 메서드를 활용해도 좋을 것 같아.

2023-08-11 00:33 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
> +                r.viewCount,
👍

2023-08-11 00:33 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java
> +    }
하드 코딩을 피하는 방법은 없었을까..?

2023-08-11 00:33 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantLikeAcceptanceTest.java
> +
로그인 정보 없는 경우에 대한 테스트도 있으면 좋을 것 같아!

2023-08-11 00:33 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java
> +            // given
복잡해도 꼭 필요한 테스트였는데 잘 작성해줬네👍👍

2023-08-11 00:33 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/common/SeedData.java
>                  음식점사진("로이스2호점 - 2", 로이스2호점, "로이스")
이 부분은 왜 달라진거야?

2023-08-11 01:44 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +        List<Object[]> results = restaurantLikeRepository.countLikesByRestaurantIds(restaurantIds);
나도 로이스 말대로 따로 객체로 표현하는 게 좋을 것 같아

2023-08-11 02:00 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +    private Map<Long, Integer> initializeLikeCount(List<Long> restaurantIds) {
음식점에 좋아요가 하나도 없으면 그냥 행이 없어서 기본으로 0으로 초기화해줘야했어!

2023-08-11 02:02 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +            Integer likeCount = ((Number) result[1]).intValue();
jpa projection 활용해서 고쳤어!

2023-08-11 02:10 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +        List<Object[]> results = restaurantLikeRepository.countLikesByRestaurantIds(restaurantIds);
jpa projection 써서 바꿨어!

2023-08-11 02:28 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryFacade.java
> +        );
이거 메서드는 orElseGet으로 했고 값 리턴하는거는 orElse했어.

```
Page<RestaurantQueryResponse> restaurantQueryResponse = memberId.map(
                id -> restaurantQueryService.findAllWithMemberId(
                        restaurantSearchCond,
                        locationSearchCond,
                        pageable,
                        id
                )).orElseGet(() -> restaurantQueryService.findAll(restaurantSearchCond, locationSearchCond, pageable));

        return Optional.ofNullable(restaurantSearchCond.celebId())
                .map(celebId -> relocateByCelebId(restaurantQueryResponse, celebId))
                .orElse(restaurantQueryResponse);
```

2023-08-11 03:09 UTC, odo27 commented on backend/src/test/java/com/celuveat/common/SeedData.java
>                  음식점사진("로이스2호점 - 2", 로이스2호점, "로이스")
이미지 정렬 순서 검증하려구!

2023-08-11 05:29 UTC, TaeyeonRoyce approved these changes

2023-08-11 05:30 UTC, kdkdhoho approved these changes
👍

2023-08-11 05:30 UTC, shin-mallang approved these changes

2023-08-11 05:32 UTC, merged