refactor: 음식점 전체 조회 중복 코드 리팩토링
woowacourse-teams/2023-celuveat pull request #324
Opened 2023-08-11 16:46 UTC by shin-mallang

## ✨ 요약
```
미안.. 이게 내 최선이었어..
맘에 안들면 좀 더 생각해보자..
```

<br><br>

## 😎 해결한 이슈
- close #313 

<br><br>

2023-08-13 01:06 UTC, TaeyeonRoyce reviewed
리팩토링 하느라 고생 많았어!
전반적으로 많이 정돈되어서 읽기 편했어!!👍👍

코멘트 남겼는데, 말랑 의견도 알려줘!

2023-08-13 01:06 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
> +    ) {
순서 👍

2023-08-13 01:06 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
> +                celebId);
```suggestion
        RestaurantWithCelebAndImagesDetailResponse result = 
            restaurantQueryFacade.findRestaurantDetailById(restaurantId,celebId);
```

2023-08-13 01:06 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
> +            @PageableDefault(size = 18) Pageable pageable
상수 안해주는 게 더 좋아보인다!

2023-08-13 01:06 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
> +            @PageableDefault(size = 4) Pageable pageable
👍

2023-08-13 06:56 UTC, kdkdhoho requested changes
너무너무 고생 많았어 말랑~
덕분에 코드 너무 깔끔해졌다. 일부 코멘트만 확인 부탁해!

2023-08-13 06:56 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/mapper/RestaurantMapper.java
> +public class RestaurantMapper {
나도 **Mapper**는 단순히 값들을 Response 객체로 **Mapping 해주는 역할**만 가지면 좋을 것 같아.
Service는 Repo에서 값들을 조회하고, Mapper에서는 단순히 Mapping만 해주는!
그러면 `Relocator`처럼 static 메서드로 사용할 수도 있을 것 같네

2023-08-13 06:56 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
> +    public Page<RestaurantWithDistance> getRestaurantsNearByRestaurantId(
특정 음식점을 제외하는 로직이 여기로 옮겨졌구나.
근데 저번에 말랑이 [리뷰](https://github.com/woowacourse-teams/2023-celuveat/pull/292#discussion_r1288078188)남겨줬던 내용인데, 메서드 네이밍을 통해 '특정 음식점을 제외한다는 것'을 알 수 없을 것 같아.
변경 부탁해요~

2023-08-13 06:56 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
> +            @PageableDefault(size = 18) Pageable pageable
22

2023-08-14 12:54 UTC, odo27 approved these changes
리팩토링 한다고 고생 많았어!! 진짜 너무 깔끔해졌다 👍👍

2023-08-14 12:54 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryFacade.java
> +        );
```
RestaurantWithCelebAndImagesDetailResponse response =
                restaurantQueryService.findRestaurantDetailById(restaurantId);
```
이거 어때?

2023-08-14 19:48 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/mapper/RestaurantMapper.java
> +public class RestaurantMapper {
나도 요걸 조금 고민했는데, Mapper를 두지 않으면 Mapper 내부 메서드들이 모두 Service로 옮겨지게 되는데 이게 너무 복잡하더라구..!!
ㅠㅠ 그냥 Service로 옮길까?

2023-08-14 19:49 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
>          Page<RestaurantWithDistance> restaurantsWithDistance = restaurantQueryRepository.getRestaurantsWithDistance(
=는 위에 아니었나?

2023-08-14 19:49 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
> +        Page<RestaurantWithDistance> restaurantsWithDistance = restaurantQueryRepository.getRestaurantsNearByRestaurantId(
저도 위에 썼었어용!

2023-08-14 19:56 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/dto/RestaurantLikeQueryResponse.java
> +    }
이거 of보다 빌더가 가독성이 더 좋아서 이렇게 한건데, 되돌릴까?

2023-08-14 19:58 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/dto/RestaurantWithCelebAndImagesSimpleResponse.java
>      ) {
RestaurantIdWithLikeCount의 count가 Long으로 되어있어서..!!
바꿀게!

2023-08-14 19:59 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/dto/RestaurantWithCelebAndImagesSimpleResponse.java
>      ) {
빌더는 가독성!

2023-08-14 21:10 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/dto/RestaurantWithCelebAndImagesDetailResponse.java
> +public record RestaurantWithCelebAndImagesDetailResponse(
아예 네이밍 바꿨어!

2023-08-14 21:10 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/dto/RestaurantWithCelebAndImagesSimpleResponse.java
> +        Long likeCount,
이게 막 테스트나 이곳저곳에서 어디서는 Long 어디서는 Interger로 받아서..!! 캐스팅 편하게 할라고 했었어

2023-08-14 21:12 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
> +    public Page<RestaurantWithDistance> getRestaurantsNearByRestaurantId(
나 근데 이걸 조금 생각을 해봤는데, 특정 음식점의 `근처 음식점`이라는 것 자체가 특정 음식점을 제외한다는 의미를 내포하는거 아닐까? 하는 생각이 들었는데 어떻게 생각해??

2023-08-14 21:12 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryFacade.java
> +        );
오키!!

2023-08-15 09:27 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/application/dto/RestaurantLikeQueryResponse.java
> +    }
가독성도 좋지만 빌더가 등장해서 궁금했어
계속 Response쪽에는 of 생성자로 해결했어서!

빌더가 명명인자처럼 사용 할 수 있기도 한데,
일관되게 보이는게 이해하기 편했던거 같아!

2023-08-15 09:29 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/application/mapper/RestaurantMapper.java
> +public class RestaurantMapper {
👍
Mapper 성격이 강한 로직이 Service로 다시 돌아가긴 하지만 그 방향이 낫다고 생각해!!

2023-08-16 01:27 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
>          Page<RestaurantWithDistance> restaurantsWithDistance = restaurantQueryRepository.getRestaurantsWithDistance(
말랑 잘 알고 있나 확인해봤어 ㅎ

2023-08-16 01:28 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
> +    public Page<RestaurantWithDistance> getRestaurantsNearByRestaurantId(
그것도 맞는 말이라 나도 동감해! 모두가 그 의미를 이해한다면 굳이 명시 안해줘도 될 것 같아

2023-08-16 01:36 UTC, kdkdhoho approved these changes
너무너무 고생많았어 말랑 👍

2023-08-16 01:36 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantLikeAcceptanceSteps.java
> +            RestaurantSimpleResponse restaurantWithCelebsAndImagesSimpleResponse
얘 변수명 안바꼈다!

2023-08-16 01:36 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantLikeAcceptanceTest.java
> +        RestaurantSimpleResponse restaurantWithCelebsAndImagesSimpleResponse1 = 전체_음식점.get(1);
얘네도!

2023-08-16 01:36 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/restaurant/domain/RestaurantQueryRepositoryTest.java
> +        for (RestaurantSimpleResponse restaurantWithCelebsAndImagesSimpleResponse : seed) {
얘도

2023-08-16 01:36 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/restaurant/fixture/LocationFixture.java
> +            RestaurantSimpleResponse restaurantWithCelebsAndImagesSimpleResponse
얘ㄷ도

2023-08-16 01:36 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/restaurant/fixture/RestaurantFixture.java
> +            Long celebId, RestaurantSimpleResponse restaurantWithCelebsAndImagesSimpleResponse
얘도

2023-08-16 01:37 UTC, TaeyeonRoyce approved these changes

2023-08-16 01:42 UTC, merged