feat: 카카오 oauth 회원탈퇴 api 구현
woowacourse-teams/2023-celuveat pull request #334
Opened 2023-08-13 12:01 UTC by kdkdhoho

## ✨ 요약
1. 카카오 로그아웃 API 기능 관련 메서드 리팩터링 -> 불필요한 반환 제거, 개행 스타일 변경, 혼란을 야기할 변수명 수정 ()
2. 카카오 회원탈퇴 API 구현했습니다. ()

<br>

## 😎 해결한 이슈
- close #300 

<br>

## 😎 관련한 이슈
- #301 

<br>

2023-08-14 04:13 UTC, TaeyeonRoyce approved these changes
도기, 일관성도 잘 맞추고 깔끔해서 좋아
리뷰할 내용이 딱히 없네!
고생 많았어~!

2023-08-14 04:13 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/auth/presentation/OauthController.java
> +    }
👍

2023-08-14 08:52 UTC, shin-mallang requested changes
고생했어 도기!!! 코드 너무 깔끔해서 커멘트 달 게 없넹!

2023-08-14 08:52 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/auth/presentation/OauthController.java
> +    private Long getOauthMemberId(HttpSession session) {
이거 메서드 순서를 logout 바로 아래로 옮겨주면 좋을 것 같아!

2023-08-14 13:28 UTC, odo27 approved these changes
도형 진짜 짱이야! 외부 API 쓰는것도 야무지구 기존 코드 잘 활용해서 확장성 있게 구현한 거 같아 👍

2023-08-14 13:28 UTC, odo27 commented on backend/src/main/java/com/celuveat/auth/application/OauthService.java
> +    public void withDraw(OauthServerType oauthServerType, Long oauthMemberId) {
이거 한단어 아닌가? `withdraw` 어때?

2023-08-14 13:28 UTC, odo27 commented on backend/src/main/java/com/celuveat/auth/presentation/OauthController.java
> +    }
```
 @DeleteMapping("/withdraw/{oauthServerType}")
 ResponseEntity<Void> withdraw(@PathVariable OauthServerType oauthServerType, @Auth Long memberId) {
     oauthService.withDraw(oauthServerType, memberId);
     return ResponseEntity.noContent().build();
 }
```

이렇게 하고 `AuthInterceptor` 에 afterCompletion 구현해서 `session.invalidate()` 해주는 거 어때? 로그아웃도 마찬가지루
```
    @Override
    public void afterCompletion(
            HttpServletRequest request,
            HttpServletResponse response,
            Object handler,
            Exception ex) {
        if (request.getRequestURI().matches("세션 지워야 하는 uri 정규 표현식")) {
            HttpSession session = request.getSession(false);
            session.invalidate();
        }
    }
```

2023-08-16 02:03 UTC, shin-mallang approved these changes

2023-08-16 02:20 UTC, merged