feat: 회원정보 조회 기능 구현
woowacourse-teams/2023-celuveat pull request #335
Opened 2023-08-14 02:12 UTC by odo27

## ✨ 요약
```
회원정보 (닉네임, 프로필) 조회 기능 구현했습니다.
```

<br><br>

## 😎 해결한 이슈
- close #319 

<br><br>

2023-08-14 02:29 UTC, kdkdhoho requested changes
깔끔하네 👍
몇 코멘트만 확인 부탁해욤

2023-08-14 02:29 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/acceptance/auth/ProfileAcceptanceTest.java
> +        Mockito.when(oauthService.login(KAKAO, "abcd")).thenReturn(member.id());
[Tecoble의 인수테스트 관련 글](https://tecoble.techcourse.co.kr/post/2020-09-15-test-isolation/)에서 `인수 테스트의 목적 자체가 실제 운영 환경과 같은 조건에서 테스트하는 것을 기대하기 때문에 Mock 프레임워크를 사용하지 않고, 실제 데이터베이스를 사용해야 그 조건을 충족할 수 있다.` 라는 말이 있어.

위 테스트는 인수 테스트인데 Service 계층을 Mocking 하면 Controller 단위 테스트가 된다고 생각하는데, 오도는 어떻게 생각해?

2023-08-14 02:29 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/acceptance/auth/ProfileAcceptanceTest.java
> +    }
얘도 Steps로 빼는건 어때?

2023-08-14 02:29 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/auth/application/ProfileServiceTest.java
> +@DisplayName("프로필서비스(ProfileService) 은(는)")
순서가 안맞아용

2023-08-14 02:29 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/auth/application/ProfileServiceTest.java
> +        // then]
이상한 게 껴있다!

2023-08-14 02:47 UTC, odo27 commented on backend/src/test/java/com/celuveat/acceptance/auth/ProfileAcceptanceTest.java
> +        Mockito.when(oauthService.login(KAKAO, "abcd")).thenReturn(member.id());
일단 mocking을 하지 않고 테스트하려면 카카오에 로그인 하는 부분 (아이디, 패스워드 입력하는 부분)을 코드로 옮겨야 하는데 방법을 모르겠어.. 그리고 카카오 oauth 코드를 가져오는 부분을 mocking 한 것이고 실제로 세션을 만들고 해당 세션 아이디로 요청을 보내는 부분까지는 다 테스트되고 있어서 카카오에서 제공하는 api 부분은 테스트하지 않아도 괜찮다고 생각했어.

2023-08-14 03:13 UTC, odo27 commented on backend/src/test/java/com/celuveat/acceptance/auth/ProfileAcceptanceTest.java
> +    }
로그인 관련 부분 Steps로 빼서 코드 많이 줄였어!

2023-08-14 04:21 UTC, TaeyeonRoyce approved these changes
오도 고생많았어!
Member랑 Profile로 분리한 거 좋은것같아!👍

2023-08-14 04:21 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/auth/application/ProfileService.java
> +}
Service 분리 좋은 것 같아!👍

2023-08-14 05:49 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/acceptance/auth/ProfileAcceptanceTest.java
> +        Mockito.when(oauthService.login(KAKAO, "abcd")).thenReturn(member.id());
아 모킹 처리한 부분이 oauth login인걸 못봤네! 그러면 좋은 것 같아!! 미안미안 🥲

2023-08-14 05:50 UTC, kdkdhoho approved these changes
모킹한 부분이 Oauth 로그인하는 부분인 걸 놓쳤네 😅
코드 깔끔합니다 고생했어 오동 👍

2023-08-14 08:58 UTC, shin-mallang requested changes
고생했어 오도!!!
우선 아래꺼 리뷰 다 달기 전에 profile로 분리하는 거에 대해서 의견을 좀 더 나누면 좋을 것 같아

2023-08-14 08:58 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/auth/application/ProfileService.java
> +public class ProfileService {
조회인데 queryService는 어떨까?
추가로
Profile 말고 MemberService로 바꾸는 건 어떻게 생각해?
profile 자체가 하나의 도메인이 아니라 그냥 member 중 일부인데, 이걸 ProfileService로 만드는 게 조금 애매한 것 같아

2023-08-15 09:31 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/auth/application/ProfileService.java
> +public class ProfileService {
말랑 의견 들어보니 맞는거 같아ㅋㅎㅋㅎ 
Profile이란 단어로 시작하는 `ProfileService`를 보니깐 되게 도메인 같네.
유스케이스 별로 Service 분리한게 좋았던건데 이건 지금 고려할 사항은 아닌것같아.

`Member(Query)Service`로 가는게 더 좋아!!

2023-08-16 02:39 UTC, shin-mallang approved these changes

2023-08-16 02:40 UTC, odo27 commented
#316  에서 동시에 머지

2023-08-16 02:40 UTC, closed without merging