feat: 리뷰 crud api 구현
woowacourse-teams/2023-celuveat pull request #337
Opened 2023-08-14 06:58 UTC by odo27

## ✨ 요약
```
리뷰 CRUD API 구현했습니다
```

<br><br>

## 😎 해결한 이슈
- close #316 

<br><br>

2023-08-14 09:03 UTC, shin-mallang requested changes
고생했어 오도!!! 리뷰 확인 부탁해!

2023-08-14 09:03 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantReviewService.java
> +    public Long saveReview(SaveReviewRequest request, Long memberId, Long restaurantId) {
create(SaveReviwRequest request) 로만 하는게 더 깔끔하고 좋아보여!

2023-08-14 09:03 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantReviewService.java
> +    public void updateReview(UpdateReviewRequest request, Long reviewId, Long memberId, Long restaurantId) {
ditto

2023-08-14 09:03 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantReviewService.java
> +        review.updateContent(request.content());
validate는 Review의 update 메서드 안으로 올껴주는게 좋을 것 같아!

2023-08-14 09:03 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantReviewService.java
> +        validateRequest(review, memberId, restaurantId);
메서드이름
파라미터
검증로직 다 위 리뷰랑 동일해

2023-08-14 09:03 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
> +    }
ReviewController를 만들고 쿼리 파라미터로 필터링 하는건 어떻게 생각해?

2023-08-15 09:52 UTC, TaeyeonRoyce requested changes
오도, 테스트까지 고생 많았어!
리뷰 남겼으니 한 번 확인해줘~!

추가로, 달라져야 하는 DB스키마에 대해서 간단한게 공지해주면 이해하기 더 좋을 것 같아!
그리고 commit도 #319 에서 이어진거 같은데 #316 관련된 것만 지정해줬으면 보는 사람이 편할듯!

2023-08-15 09:52 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantReviewService.java
> +    public Long saveReview(SaveReviewRequest request, Long memberId, Long restaurantId) {
\+ `SaveReviewCommand`로 application용 dto를 만들어도 좋을 것 같아!

```java
public record SaveReviewCommand(String content, Long memberId, Long restaurantId) {}
```

2023-08-15 09:52 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
> +    }
나누는김에 like도 나누자!

2023-08-15 09:52 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/domain/review/RestaurantReviewRepository.java
> +    List<RestaurantReview> findAllByRestaurantIdOrderByCreatedDateDesc(Long restaurantId);
👍

2023-08-15 09:52 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/domain/review/RestaurantReview.java
> +public class RestaurantReview extends BaseEntity {
업데이트 날짜도 추가해주면 좋을 것 같아!

2023-08-15 09:52 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantReviewService.java
> +    }
update랑 delete를 할 때, restaurant도 검증해야하는지 모르겠어.
Review도메인 관점으로만 보면 Review Id만으로도 충분하지 않을까?

2023-08-15 09:52 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantReviewService.java
> +        review.updateContent(request.content());
굿굿

2023-08-15 09:52 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/auth/presentation/AuthInterceptor.java
> +    }
이 부분도 API 설계로 해결 해볼 수 있을 것 같아!
uri에서 regex로 특정 요청만 분리한다는건 다른 성격의 자원을 묶어서 생긴 문제같아

2023-08-15 09:52 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantReviewAcceptanceTest.java
> +        응답_상태를_검증한다(응답, 권한_없음);
👍
이 집 테스트 잘하네요

2023-08-16 01:57 UTC, kdkdhoho approved these changes
CRUD 모두 한다고 고생했어 오동~ 👍

2023-08-16 01:57 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/presentation/ReviewController.java
> +            @RequestParam("restaurantId") Long restaurantId
name 속성 없어도 될 것 같은데 어때?

2023-08-16 01:57 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/auth/application/MemberQueryServiceTest.java
> +@DisplayNameGeneration(ReplaceUnderscores.class)
순서!

2023-08-16 02:02 UTC, shin-mallang requested changes

2023-08-16 02:02 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/auth/application/MemberQueryService.java
> +    public MemberQueryResponse getProfile(Long memberId) {
이거 profile 조회하는데 MemberQueryResponse 반환하는게 이상한것같아

2023-08-16 02:02 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/auth/presentation/AuthInterceptor.java
> +    private static final String REVIEW_URI_REGEX = "^\\/api\\/reviews.*";
이거 수정 부탁해!

2023-08-16 02:04 UTC, odo27 commented on backend/src/main/java/com/celuveat/auth/application/MemberQueryService.java
> +    public MemberQueryResponse getProfile(Long memberId) {
MemberProfileResponse로 바꿨어! 👍

2023-08-16 02:10 UTC, odo27 commented on backend/src/main/java/com/celuveat/auth/presentation/AuthInterceptor.java
> +    private static final String REVIEW_URI_REGEX = "^\\/api\\/reviews.*";
이거 AuthInterceptor path 관련 문제 이슈로 빼놓을께! 👍

2023-08-16 02:12 UTC, odo27 commented on backend/src/main/java/com/celuveat/auth/presentation/AuthInterceptor.java
> +    }
이거 이슈로 뺐어!

2023-08-16 02:12 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/application/RestaurantReviewService.java
> +    }
API 설계 새로했어!

2023-08-16 02:14 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/domain/review/RestaurantReview.java
> +public class RestaurantReview extends BaseEntity {
이슈 파놨어!

2023-08-16 02:52 UTC, shin-mallang approved these changes

2023-08-16 02:52 UTC, TaeyeonRoyce approved these changes

2023-08-16 02:52 UTC, merged