feat: 회원 탈퇴 기능 및 위시리스트 명세에 맞게 기능 수정
woowacourse-teams/2023-celuveat pull request #347
Opened 2023-08-15 02:42 UTC by turtle601

## ✨ 요약
- [ ] 위시리스트 명세에 맞게 기능 수정 -> 위시리스트의 좋아요를 프론트에서 관리 (데이터를 따로 받지 않음)
- [ ] 회원 탈퇴 기능 구현 -> 탈퇴 페이지를 만들어서 구현 
- [ ] 탈퇴 페이지 + 로그인 페이지 반응형 구현

## 기능 구현
![스크린샷 2023-08-15 오전 11 38 21](https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/a084c974-3d55-42b0-8490-58ec6378d24b)

![스크린샷 2023-08-15 오전 11 41 13](https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/7807b36a-9011-4454-8a6e-a01fdcee4029)

![스크린샷 2023-08-15 오전 11 42 11](https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/03b9b252-8bf2-42a6-bf96-cdae1a7a055b)

## 😎 해결한 이슈
- close #342 #341 #343 

<br><br>

2023-08-15 06:44 UTC, D0Dam requested changes
리뷰 남겼습니다! 작업 열심히 하시네요..ㅎㅎ 👍 
확인하시고 반영 및 답글 부탁드려요! 화이팅~!

2023-08-15 06:44 UTC, D0Dam commented on frontend/src/App.tsx
> +        <Route path="/withdrawal" element={<WithdrawalPage />} />
이건 무슨 페이지이죠?

2023-08-15 06:44 UTC, D0Dam commented on frontend/src/api/User/index.ts
> +    withCredentials: true,
👍

2023-08-15 06:44 UTC, D0Dam commented on frontend/src/components/@common/Header/Header.tsx
> +    }
사소하긴 한데 기존 꺼에서 다시 중괄호를 씌운 이유가 있나요? 밑에거는 안씌웠길래...

2023-08-15 06:44 UTC, D0Dam commented on frontend/src/components/WithdrawalModalContent/WithdrawalModalContent.tsx
> +        <TextButton type="button" text="탈퇴하기" colorType="dark" width="100%" onClick={deleteUser} />
이건 ui/ux 적인 이야기인데, 저희 서비스 운영 입장에서 사용자가 빠져나가는 것은 좋지 않겠죠?
그래서 색의 강조가 지금 탈퇴하기에 맞추어져 있는데 취소하기에 `colorType=dark` 를  써서 강조했으면 좋겠어요. (두 버튼 색깔이 바뀌었으면 좋겠다는 이야기)

2023-08-15 06:44 UTC, D0Dam commented on frontend/src/hooks/server/useToggleLikeNotUpdate.ts
> +  const { value: isLiked, toggle: toggleIsLiked } = useBooleanState(true);
이 훅을 사용하는 곳에서는 무조건 음식점 좋아요가 눌려져 있다라는 가정인가요?

그렇게 되면 상세 페이지에서 쓰지 못할 것 같은데요..

2023-08-15 06:54 UTC, turtle601 commented on frontend/src/hooks/server/useToggleLikeNotUpdate.ts
> +  const { value: isLiked, toggle: toggleIsLiked } = useBooleanState(true);
사실 도담 코드 보기 전에 코드 수정한 내용이라;;;

```ts
 const { value: isLiked, toggle: toggleIsLiked } = useBooleanState(restaurant.isLiked ?? true);
```

이런 식으로 새로 수정하려고 생각했어요!!

2023-08-15 06:59 UTC, turtle601 commented on frontend/src/App.tsx
> +        <Route path="/withdrawal" element={<WithdrawalPage />} />
![스크린샷 2023-08-15 오후 3 58 53](https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/3e1945e7-16ba-41ea-90e0-11c8d17c897d)

ㅎㅎ

2023-08-15 07:00 UTC, turtle601 commented on frontend/src/components/@common/Header/Header.tsx
> +    }
습관적으로 중괄호 씌우고 이를 수정을 안한 것 같습니다!! 

> 수정하겠습니다!! 👍

2023-08-15 07:02 UTC, turtle601 commented on frontend/src/components/WithdrawalModalContent/WithdrawalModalContent.tsx
> +        <TextButton type="button" text="탈퇴하기" colorType="dark" width="100%" onClick={deleteUser} />
회원가입 탈퇴 ux에 대해서도 한 번 알아보았습니다!!
[쉬운 해지가 탈퇴가 좋은 UX일까??](https://weeklyuxuichallenge.oopy.io/d2d4cdb8-c6b9-4b72-847b-b5055c6f6fdc)

색 강조를 통해서라도 탈퇴하기 조금이라도 어렵게 하는게 좋을 것 같네요 ㅎㅎ 👍

2023-08-15 08:09 UTC, D0Dam approved these changes
답글 확인했어요! approve 하겠습니다~!

2023-08-16 00:23 UTC, turtle601 commented
> 답글 확인했어요! approve 하겠습니다~!

넵, 모두 수정했습니다!!

2023-08-16 01:25 UTC, shackstack approved these changes

2023-08-16 01:31 UTC, merged