feat: 레스토랑 카드 컴포넌트 구현
woowacourse-teams/2023-celuveat pull request #49
Opened 2023-07-09 07:32 UTC by shackstack

<img width="359" alt="스크린샷 2023-07-09 오후 4 31 19" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/325d181f-ad9b-4968-b13e-3ece3e8cbffc">

close #46 
close #48

2023-07-09 08:12 UTC, D0Dam requested changes
svg 관련 webpack 설정도 담겨져 있군요!
카드 관련 리뷰를 좀 작성했습니다! 확인 부탁드려요~~!

2023-07-09 08:12 UTC, D0Dam commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +    <StyledDiv>
최상단 Styled Components는 네이밍을 Container 정도로 가져가 주는 것이 어떨까요?
```suggestion
    <StyledContainer>
```

2023-07-09 08:12 UTC, D0Dam commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +          </StyledRestaurantName>
제가 이해한 의도로는 같은 스타일 컴포넌트를 재활용하려 한 것 같은데, 이 때문에 뭔가 `<StyledRestaurantName>` 네이밍이 안의 자식 요소가 담고있는 정보와는 맞지 않는 것 같아요. 별점과 리뷰를 나타내는 네이밍을 따로 줘봐도 좋을 것 같아요!

2023-07-09 08:12 UTC, D0Dam commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +  flex: 1;
이건 무슨 용도죠?

2023-07-09 08:12 UTC, D0Dam commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +  gap: 8px;
flex에서 gap 을 사용할 경우 gap의 방향을 명시해 주었으면 좋겠어요!

ex) column-gap, row-gap

2023-07-09 08:12 UTC, D0Dam commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +  font-weight: normal;
밑의 스타일과 겹치는 리뷰입니다.

`font-weight: normal;` 는 기본값이므로 제외하는 것이 어떨까요?

2023-07-10 03:37 UTC, turtle601 commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +  box-sizing: border-box;
box-sizing 같은 경우 GlobalStyle에서 미리 선언하는 게 좋을 거 같아요!!

2023-07-10 03:37 UTC, turtle601 commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +  height: 192px;
height 속성에는 모두 `rem` 속성이 아닌 `px`을 사용하고 있어요. 혹시 이유가 있을까요??

2023-07-10 03:37 UTC, turtle601 commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +  border-radius: ${BORDER_RADIUS.sm};
👍

2023-07-10 03:37 UTC, turtle601 commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +  color: var(--gray-3);
모든 컴포넌트에 스타일 네이밍과 스타일을 모두 부여하셨군요!!

font-size 속성과 color 속성 모두 cascading이 되는 속성으로 알고 있습니다!! 
fontInfo 컴포넌트에 default 속성을 준다면 많은 컴포넌트에게 스타일을 주지 않아도 됩니다. 

그럼에도 불구하고 모든 컴포넌트에 스타일 네이밍과 스타일을 모두 부여하신 이유가 궁금합니다!

2023-07-10 03:37 UTC, turtle601 commented on frontend/.storybook/main.ts
> +  webpackFinal: async config => {
설명이 시급합니다... ㅎㅎㅎ

2023-07-10 04:14 UTC, shackstack commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +  color: var(--gray-3);
우선 가독성 측면에서 각각 네이밍을 해주는 것이 좋을 것 같아서입니다.
물론 cascading을 통해 하위 컴포넌트의 스타일을 다룰 수 있으나 단순하게 <div>로 표현하면 무슨 역할인지를 파악하는데 시간이 오랠 것 같아서요.

2023-07-10 04:49 UTC, shackstack commented on frontend/src/components/RestaurantCard/RestaurantCard.tsx
> +  height: 192px;
피그마 시안대로 하다보니 rem적용을 잊었습니다. 적용시키겠습니다.

2023-07-10 07:38 UTC, turtle601 approved these changes

2023-07-10 07:45 UTC, D0Dam approved these changes

2023-07-10 07:45 UTC, merged

2023-07-10 07:50 UTC, turtle601 approved these changes
변경사항 모두 확인해주셔서 approve 합니다!!