refactor: 서브쿼리 분리를 통해 쿼리를 개선한다
woowacourse-teams/2023-celuveat pull request #523
Opened 2023-09-26 01:24 UTC by shin-mallang

## ✨ 요약
음식점 조회 시 발생하는 서브쿼리를 분리했습니다.
이때 좋아요 수의 경우 역정규화를 통해 개선했습니다.
이로 인해 동시성 문제가 발생할 수 있으며, 이를 처리하기 위한 이슈를 생성해 두었습니다.
테이블을 수정하는 SQL은 다음과 같습니다.
```sql
ALTER TABLE restaurant ADD like_count INT;

UPDATE restaurant SET like_count = (
    SELECT COUNT(*)
    FROM restaurant_like
    WHERE restaurant_id = restaurant.id
);
```

추가로 인덱스도 걸어주어야 하며, 이 역시 이슈로 따로 파두었습니다.

PS - 도기 테스트코드 리팩토링 화이팅...

<br><br>

## 😎 해결한 이슈
- close #517 

<br><br>

2023-09-26 06:30 UTC, odo27 requested changes
말랑 서브 쿼리 분리해낸다고 고생했어 👏👏👏
항상 작업 내용을 잘 나눠서 커밋해줘서 리뷰하기 편했어 👍
몇개 코멘트 남겼으니 확인해줘!

2023-09-26 06:30 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantSimpleResponseDao.java
> +                .collect(Collectors.groupingBy(it -> it.restaurant().id()));
혹시 이부분을 Map으로 그룹핑하는 이유가 있을까?
existLike에서 containsKey만 사용한다면 Set을 활용하는 건 어때?

2023-09-26 06:30 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantSimpleResponseDao.java
> +    private Map<Long, Boolean> getIsLikedGroupByRestaurantsId(@Nullable Long memberId, List<Long> restaurantIds) {
```
    private Map<Long, Boolean> getIsLikedGroupByRestaurantsId(@Nullable Long memberId, List<Long> restaurantIds) {
        if (memberId == null) {
            return restaurantIds.stream()
                    .collect(Collectors.toMap(Function.identity(), it -> false));
        }
        Set<Long> likedRestaurantIds =
                restaurantLikeQueryDaoSupport.findAllByMemberIdAndRestaurantIdsIn(memberId, restaurantIds).stream()
                        .map(it -> it.restaurant().id())
                        .collect(Collectors.toSet());
        return restaurantIds.stream()
                .collect(Collectors.toMap(Function.identity(), likedRestaurantIds::contains));
    }
```

뭔가 이런 느낌으로 개선해보면 어떨까?

2023-09-26 06:30 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantSimpleResponse.java
> +                (restaurantImages != null) ? restaurantImages.stream().map(RestaurantImageQueryResponse::of).toList() : Collections.emptyList()
조건문을 `restaurantImages == null` 인 건 어때?

2023-09-26 06:30 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/command/domain/Restaurant.java
> +        this.likeCount += 1;
++, -- 쓰는 거 어때?

2023-09-26 06:30 UTC, odo27 commented on backend/src/main/java/com/celuveat/restaurant/command/application/RestaurantLikeService.java
>      }
👍👍👍

2023-09-26 07:07 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantSimpleResponseDao.java
> +                restaurantIds);
자동 정렬 된 것 같당

2023-09-26 07:07 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantSimpleResponseDao.java
> +                .collect(Collectors.groupingBy(it -> it.restaurant().id()));
이거 나중에 음식점별로 좋아요 세팅해줘야해서 map 써야 편해!!

2023-09-26 07:08 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantSimpleResponseDao.java
> +    private Map<Long, Boolean> getIsLikedGroupByRestaurantsId(@Nullable Long memberId, List<Long> restaurantIds) {
나는 지금이 오히려 가독성이 더 좋다고 생각해..?
조금 더 생각해볼게 고마워 오도!

2023-09-26 07:09 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantSimpleResponse.java
> +                (restaurantImages != null) ? restaurantImages.stream().map(RestaurantImageQueryResponse::of).toList() : Collections.emptyList()
어 음 근데 이거 어차피 개선해야 해서 일단 넘어가도 괜찮지않을까?
딱히 상관 없으니 반영은 해둘게!

2023-09-26 07:10 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/command/domain/Restaurant.java
> +        this.likeCount += 1;
오키

2023-09-26 07:10 UTC, TaeyeonRoyce requested changes
말랑 고생했어~! 리팩토링 힘들었을텐데 잘 만들어줬네👍
코멘트 남겨뒀으니 확인 부탁해~!

2023-09-26 07:10 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/query/dao/support/RestaurantLikeQueryDaoSupport.java
> +    );
```suggestion
    List<RestaurantLike> findAllByMemberIdAndRestaurantIdIn(
            Long memberId,
            List<Long> restaurantIds
    );
```
이렇게도 되는 것 같은데 `support`를 최대한 활용하는 방향으로 쓰는게 어때?

2023-09-26 07:10 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantSimpleResponse.java
> +                (restaurantImages != null) ? restaurantImages.stream().map(RestaurantImageQueryResponse::of).toList() : Collections.emptyList()
이건 왜 수정한거야?

2023-09-26 07:10 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/restaurant/query/dao/RestaurantWithDistanceDaoTest.java
> +
공백 제거좀!

2023-09-26 08:00 UTC, kdkdhoho requested changes
궁금한 거 질문 남겼어용
쿼리랑 테스트는 언제봐도 머리아프네,,

2023-09-26 08:00 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantSimpleResponse.java
> +                (restaurantImages != null) ? restaurantImages.stream().map(RestaurantImageQueryResponse::of).toList() : Collections.emptyList()
restaurantImages가 null일 수가 있는지 궁금해.
DB에서 꺼내올 때 값이 없으면 빈 리스트가 반환되지 않나?

2023-09-26 11:26 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/command/domain/Restaurant.java
> +        this.likeCount += 1;
앗 그냥 별 상관없을 것 같아서 이렇게 가도 괜찮
을까?

2023-09-27 01:20 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantSimpleResponse.java
> +                (restaurantImages != null) ? restaurantImages.stream().map(RestaurantImageQueryResponse::of).toList() : Collections.emptyList()
@kdkdhoho 
이거 테스트시에 이미지 없는 경우 예외 터졌었다!

2023-09-27 02:10 UTC, TaeyeonRoyce approved these changes
내 리뷰는 잘 반영 된 것 같아서 approve 할게! 👍

2023-09-27 02:35 UTC, kdkdhoho approved these changes
수고했어 말랑~
덕분에 객체 생성 관련 새로운 인사이트도 얻었네요 👍

2023-09-27 02:41 UTC, shin-mallang commented
@kdkdhoho 
바꾸고 나니 다른 코드와 통일성도 지켜지고, 어색하지 않아서 더 좋은 것 같아
고마워 도기맨👍

2023-09-27 04:06 UTC, merged