feat: 리뷰 좋아요, 신고하기 기능 추가
woowacourse-teams/2023-celuveat pull request #537
Opened 2023-09-28 11:44 UTC by turtle601

## ✨ 요약
- 리뷰 좋아요 낙관적 업데이트로 구현 (깜빡임 X)
- 리뷰 명세 변경으로 인한 ui 변경
- 그 외 ReviewModal에 중복되는 로직이 많아서 이를 리팩토링했습니다.

<br><br>

## 변경된 ui
<img width="1283" alt="스크린샷 2023-09-28 오후 8 42 35" src="https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/b973065a-96fc-42d9-bc6f-1e18161c2cdd">

-> 사진이 추가로 들어가게 되면서 2열로 할 경우 둘의 높낮이가 맞지 않을 수 있다고 판단함, 
-> 데스크탑에서도 1열로 하는 방향으로 팀원과의 논의 후 결정

## 😎 해결한 이슈
- close #528

<br><br>

2023-09-29 04:25 UTC, turtle601 commented on frontend/src/hooks/server/useRestaurantReview.ts
> +    postReviewLike: postReviewLike.mutate,
이거는  toggleRestaurantReviewLike로 대체되어서 export 하지 않아도 될 듯!!

2023-09-29 06:05 UTC, shackstack requested changes
푸만능 기능 구현하시느라 고생많으셨습니다.

몇 가지 수정해야할 부분들이 보여 말씀드릴게요!

1. 리뷰 신고하기의 placeholder가 적절하지 않습니다. 
<img width="387" alt="스크린샷 2023-09-29 오후 2 44 31" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/cfbe430a-3080-4863-bd02-849cd73de7c6">

2. 로그인을 하지 않았음에도 추천하기가 활성화 됩니다.

https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/6651719b-5a38-4269-b22f-1f75642a8561

3. 리뷰 모두 보기 기능
<img width="374" alt="스크린샷 2023-09-29 오후 2 52 52" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/2ae53170-67cc-4e15-9a25-da716dc81f6e">

현재 리뷰가 9개 보이고 있는데 리뷰 9개 모두 보기의 기능이 필요한지 모르겠습니다.

4. 위치 확인하기 기능의 위치
만약 무한스크롤 형태로 모든 리뷰를 보여주실 계획이시라면 위치 확인하기 기능이 리뷰보다 상단에 위치하는 것이 좋을 것 같아요. 

5. 수정하기, 신고하기 폼 제출 시 새로고침 현상
수정하기, 신고하기 폼 제출 후에 새로고침되는 현상이 발생하는데, 새로고침없이 토스트로 제문구를 띄우는게 더 자연스러울 것 같습니다.

2023-09-29 08:49 UTC, turtle601 commented on frontend/src/components/RestaurantReviewItem/RestaurantReviewItem.tsx
> +              <span>추천 {getReviewIsLiked(review.id) ? '취소' : '하기'}</span>
모바일에서 제가 제대로 확인을 안 한것 같네요!! 다시 한번 확인 해볼께요~~

2023-09-29 08:50 UTC, turtle601 commented
데스크탑에서는 잘 나오는데 모바일에서 해당 에러가 나오는 것 같아요!! 모바일에서 전반적으로 다시 기능 확인 후 수정해보겠습니다!!

2023-10-01 08:24 UTC, turtle601 commented
### 수정사항
- [x] 리뷰 신고하기의 placeholder가 적절하지 않습니다. -> ReviewReportForm을 새로 만들어서 수정했습니다!!
- [x] 코드 수정하면서 로그인 문제가 남아있었습니다 (Context API - useMemo 관련) -> 해결했습니다!!
- [x] 현재 리뷰가 9개 보이고 있는데 리뷰 9개 모두 보기의 기능이 필요한지 모르겠습니다. 
   -> 이건 제 로컬에서는 정상적으로 동작하고 있었습니다. 다시 한번 확인해주세요!!
- [x] 위치 확인하기 기능의 위치
   -> 이건 팀원들과의 이야기가 더 필요한 부분이라 생각됩니다!! (중요한 문제는 아니니 논의 후 수정하겠습니다)
- [x] 수정하기, 신고하기 폼 제출 시 새로고침 현상
   -> c(r)ud 리뷰 로직이 성공하였을 때 모달이 닫히고 toast ui가 열리는 식으로 구현하였습니다!!

2023-10-03 10:18 UTC, turtle601 commented
파일 업로드 시 File(Blob) 타입을 전송하게 됩니다. 
이때 MSW에서 이미지 파일(바이너리 코드)를 읽지 못해 에러가 나는 문제가 있었습니다. 

따라서 일단은 리뷰를 create, update할 때 임의의 리뷰를 작성하는 방식으로 msw 코드를 수정하였습니다!!

2023-10-04 07:16 UTC, shackstack approved these changes
푸만능 리뷰 잘 반영해주셨군요!
추가적으로 사진 등록하기 잘 구현해주셨는데 gap이랑 border가 있으면 좋을 것 같아요. 
피드백 반영해주시고 merge진행해주시면 감사하겠습니다. 
approve는 진행하겠습니다.

2023-10-04 07:16 UTC, shackstack commented on frontend/src/api/apiClient.ts
> +export const apiUserFilesClient = axios.create({
네이밍에 관한 부분들은 나중에 함께 얘기나눠보면 좋을 것 같네요.

2023-10-04 07:16 UTC, shackstack commented on frontend/src/assets/icons/star/empty-left-star-icon.svg
별점관련 svg파일이 5개나 있는데, filled속성을 활용하면 파일 수를 줄일 수 있을 것 같아요.

2023-10-04 07:16 UTC, shackstack commented on frontend/src/components/@common/Star/HalfStar.tsx
> +        {isFilled ? <FilledLeftStarIcon /> : <EmptyLeftStarIcon />}
<StarIcon filled={ isFilled ? #노랑 : #회색 }/>
이런식으로 표현하면 svg파일 개수를 줄일 수 있을 것 같아요.

2023-10-05 07:33 UTC, D0Dam approved these changes
리뷰 안깜빡이네요! 와우~! 너무 좋습니다.

일단 빠르게 리뷰를 쓰고 합쳐야 되는 상황이다보니 추가적으로 이런 부분이 있으면 좋겠다! 부터 적어보고 이후에 더 상세한 리뷰 더 남기도록 하겠습니다!

- 별점에 hover 시 현재 몇점인지 알 수 있었으면 좋겠어요! 사용자 경험 측면에서 이게 좋아보이네요!
- 그리고 아래와 같이 사진이 차례대로 삭제되는 것이 아닌 앞에 삭제, 뒤에 삭제 중간 삭제 순으로 삭제가 되네요..! 삭제 방향을 한 방향으로 맞추어주면 좋을 것 같은데요..?
- 추가적으로 혹시 msw 환경에서 사진 추가는.. 못해보는 거겠죠? 일단 급한건 아니니 넘가도 좋을 것 같아요!

https://github.com/woowacourse-teams/2023-celuveat/assets/51052049/59ec5ccb-d2b3-4fdf-bb64-4a29e609ee1f

위에 사항만 참고해서 추가해 주세요! 우선 approve 하겠습니다!

2023-10-05 09:01 UTC, turtle601 commented on frontend/src/components/@common/Star/HalfStar.tsx
> +        {isFilled ? <FilledLeftStarIcon /> : <EmptyLeftStarIcon />}
> 수정했습니다!!

2023-10-05 09:18 UTC, turtle601 commented
> 별점에 hover 시 현재 몇점인지 알 수 있었으면 좋겠어요! 사용자 경험 측면에서 이게 좋아보이네요!
- 사실 데스크탑에서 hover 기능을 구현을 하려고 했지만 모바일에서는 hover가 동작하지 않으니 이를 어떻게 보여줘야 될까라는 고민이 생기더라구요. 그래서 일단은 click이벤트 발생 시 별점을 매길 수 있는 기능만 구현을 해놓은 상태입니다. 
- 추가적으로 별점을 매기지 않았을 경우 등록이 되지 않는 기능도 있어요!!


> 추가적으로 혹시 msw 환경에서 사진 추가는.. 못해보는 거겠죠? 일단 급한건 아니니 넘가도 좋을 것 같아요!
아래 영상을 참조해주세요!!
https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/7ae52b4f-9d3c-44b4-8e9b-876a27f9239e

1. 이전 커밋에서 수정 기능을 수행 시 사진 삭제는 되지만 추가는 안되서 사진 업로드가 안된 것 같아요!!
- 현재는 수정을 할려고 할 경우 사진 업로드 기능을 제외해버렸습니다. (그렇게 api 명세두 바꼇어요!!)

2. 리뷰 작성하기 기능을 수행하면 리뷰에서 사진 업로드는 가능합니다!!
- 다만 내가 업로드한 이미지를 볼 수는 없고, msw 상으로 업로드한 사진의 개수 만큼 제가 저장한 임의의 사진을 업로드하는 식으로 표현했습니다!!

3. 삭제하기 순서
- 삭제한 방향 맞춰달라는게 어떤 건지 이해가 잘되지 않네요 ㅜㅜ. (제가 국어를 잘 못해요 ㅋㅋ)
사용자에게 어떤 이미지가 삭제되었는지 쉽게 알 수 있게 애니메이션 같은 걸 적용하라는 이야기 인가요??

2023-10-06 01:56 UTC, merged