feat: 카테고리 재구성
woowacourse-teams/2023-celuveat pull request #542
Opened 2023-09-30 11:01 UTC by shackstack

## ✨ 요약
```
지난 회의에서 재구성한 카테고리를 바탕으로 카테고리를 재구성하였고, 이에 따라 아이콘을 추가하면서 변경을 진행하였습니다.
또한 지도 페이지에서의 카테고리네브바 컴포넌트를 재사용하기위한 고도화도 진행하였습니다. 
```

![스크린샷 2023-09-30 오후 7 49 17](https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/79095791-bb06-4408-8695-4d4c9d2fba6a)
- 참고로 <국,국밥> 아이콘은 못구하여 한식으로 이동해야할 것 같네요...ㅎ

<br><br>

## 😎 해결한 이슈
- close #540 

<br><br>

2023-10-03 04:01 UTC, turtle601 requested changes

2023-10-03 04:01 UTC, turtle601 commented on frontend/src/constants/restaurantCategory.tsx
> +const RESTAURANT_CATEGORY: Record<string, Category> = {
배열에서 객체로 변경한 이유가 있을까요?? 
(key 값이 필요해서 변경한 줄 알았는데 사용처도 없네요.)

2023-10-05 06:06 UTC, shackstack commented
추가로 카테고리 검색 결과 페이지를 구현하였습니다. 

<img width="200" alt="스크린샷 2023-10-05 오후 3 04 49" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/537b0c67-c649-44b8-ae2c-25b6b08be063">

회의 결과를 반영하여 카테고리에 해당하는 전국 맛집들을 검색 결과에 띄워주도록 구현하였습니다.

2023-10-05 07:03 UTC, shackstack commented on frontend/src/components/CategoryNavbar/CategoryNavbar.tsx
> +        if (!includeAll && label === '전체') return null;
메인페이지에서 카테고리 BEST에 '전체'는 들어가는 것이 어울리지 않는다고 생각하였습니다.
지도페이지에서는 default값을 두었지만 메인페이지에서는 default값이 필요가 없으니까요.
구성에 관한 이야기는 회의 때 이야기해봐도 좋을 것 같습니다.

2023-10-05 07:23 UTC, D0Dam approved these changes
제가 궁금한 부분에 대해서는 푸만능이 물어봐주었네요! ㅎㅎ
디자인적인 부분..에서 좀 이야기해보고 싶지만 저도 마땅히 더 나은 디자인이 생각이 안나서 생각이 나면 그때 추가적으로 제안해볼게요! 나머지는 기존 로직 유지하면서 잘 해주신 것 같습니다! 수고하셨습니다~!

2023-10-05 11:31 UTC, turtle601 approved these changes

2023-10-05 11:31 UTC, turtle601 commented on frontend/src/components/CategoryNavbar/CategoryNavbar.tsx
> +function CategoryNavbar({
현재 사용한 CategoryNavbar는 checkbox 기능을 제공하고 있습니다.
(selected 상태를 사용해서 선택된 카테고리를 표시하고 있습니다.)
하지만 메인 페이지에서 사용한 CategoryNavbar는 해당 기능을 사용하고 있지 않습니다. 
기능만 이라도 분리를 하는 것이 좋지 않을까요?

2023-10-05 12:04 UTC, merged