feat: 상세페이지 컴포넌트 분리 및 스켈레톤 추가
woowacourse-teams/2023-celuveat pull request #556
Opened 2023-10-05 07:20 UTC by D0Dam

## ✨ 요약

다음과 같이 컴포넌트를 분리해 두었습니다.

<img width="330" alt="image" src="https://github.com/woowacourse-teams/2023-celuveat/assets/51052049/32bce71c-8495-4fa5-b338-cc5b1ef0ec4e">

이걸 정확히 어디 폴더에 둘지는 정해야 할 것 같아 우선 페이지 내의 한 폴더에서 분리해 놓았습니다.

추가적으로 스켈레톤을 추가했습니다.
우선 모바일에 대응하는 스켈레톤을 넣어놓았습니다. 따라서 모바일 환경에 대해서만 확인해주세요.
데스크톱의 경우도 추후 바로 추가하겠습니다.
<br><br>

## 😎 해결한 이슈
- close #555

<br><br>

2023-10-05 11:45 UTC, turtle601 requested changes
도담 리뷰 남겼어요!!

2023-10-05 11:45 UTC, turtle601 commented on frontend/src/pages/RestaurantDetailPage/RestaurantVideoList.tsx
> +function RestaurantVideoList({ restaurantId, celebId }: RestaurantVideoListProps) {
```tsx
 const { data: restaurantVideo } = useQuery<VideoList>({
    queryKey: ['restaurantVideo', restaurantId],
    queryFn: async () => getRestaurantVideo(restaurantId),
    suspense: true,
  });
  
     {restaurantVideo.totalElementsCount > 1 && (
        <VideoCarousel
          title={`이외에 ${restaurantVideo.currentElementsCount - 1}명의 셀럽이 다녀갔어요!`}
          videos={restaurantVideo.content.slice(1)}
        />
      )}
```

이것과
```tsx
  const { data: celebVideo } = useQuery<VideoList>({
    queryKey: ['celebVideo', celebId],
    queryFn: async () => getCelebVideo(celebId),
    suspense: true,
  });
       <VideoCarousel
        title="이 셀럽의 다른 음식점 영상"
        videos={celebVideo.content.filter(({ videoId }) => videoId !== restaurantVideo?.content[0].videoId)}
      />
```

컴포넌트를 분리하는 것에 대해서 어떻게 생각하시나요?? 
[리액트로 사고하기](https://ko.legacy.reactjs.org/docs/thinking-in-react.html)
![스크린샷 2023-10-05 오후 8 44 11](https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/173826d1-1e61-4c07-9f5a-b9c7745be022)

2023-10-06 00:45 UTC, D0Dam commented on frontend/src/pages/RestaurantDetailPage/DetailInformation.tsx
> +  const { data: restaurantVideo } = useQuery<VideoList>({
기존꺼를 유지하면서 가다보니 눈치를 못채고 있었네요 ㅎㅎ.. 바꿔놓을게요~!

2023-10-06 00:49 UTC, D0Dam commented on frontend/src/pages/RestaurantDetailPage/RestaurantVideoList.tsx
> +function RestaurantVideoList({ restaurantId, celebId }: RestaurantVideoListProps) {
저도 나누는게 좋아보이네요. 나눠서 다시 올려보겠습니다~!

2023-10-06 01:24 UTC, turtle601 approved these changes
모두 확인했습니다 approve 할게여

2023-10-06 01:24 UTC, turtle601 commented on frontend/src/pages/RestaurantDetailPage/DetailInformation.tsx
> +  const { data: restaurantVideo } = useQuery<VideoList>({
제가 착각한 부분이 있었네요 ㅜㅜ 그대로 가시죠

2023-10-06 01:25 UTC, shackstack approved these changes

2023-10-06 01:27 UTC, merged