feat: 음식점 사진 추가 api 구현
woowacourse-teams/2023-celuveat pull request #558
Opened 2023-10-05 08:46 UTC by odo27

## ✨ 요약
- 음식점 사진 추가 API 구현
- 사용자가 사진 추가 제안하는 API 구현
```
CREATE TABLE `restaurant_image_suggestion`
(
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `restaurant_id` bigint            DEFAULT NULL,
    `member_id`     bigint            DEFAULT NULL,
    `name` varchar(255) NOT NULL,
    `created_date`  timestamp(6) NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `fk_restaurant_image_suggestion_restaurant_id_from_restaurant_id` (`restaurant_id`),
    KEY `fk_restaurant_image_suggestion_member_id_from_oauth_member_id` (`member_id`),
    CONSTRAINT `fk_restaurant_image_suggestion_member_id_from_oauth_member_id` FOREIGN KEY (`member_id`) REFERENCES `oauth_member` (`id`),
    CONSTRAINT `fk_restaurant_image_suggestion_restaurant_id_from_restaurant_id` FOREIGN KEY (`restaurant_id`) REFERENCES `restaurant` (`id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 10
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;
```

<br><br>

## 😎 해결한 이슈
- close #530 

<br><br>

2023-10-05 10:13 UTC, shin-mallang requested changes
고생했어 오도~!

2023-10-05 10:13 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/auth/config/AuthConfig.java
> +                        "/images/suggest",
레스토랑 이미지인걸 좀 더 명시 못해주나?

2023-10-05 10:13 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/common/client/ImageUploadClient.java
> +    void upload(List<MultipartFile> file);
이거 default로 단일 이미지 저장 upload 호출하게 못해주나?

2023-10-05 10:13 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/common/infra/aws/AwsS3ImageUploadClient.java
> +    public void upload(final List<MultipartFile> file) {
final지워줘

2023-10-05 10:13 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/presentation/ImageController.java
> +public class ImageController {
이것도 그냥 이미지라 하면 애매한것같아

2023-10-05 10:13 UTC, shin-mallang commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantImageAcceptanceTest.java
> +        이미지_업로드를_설정한다(이미지);
이거 암시적으로 처리해줄수는 없어?
인수테스트에 껴있으면 사용자가 해야하는 것 처럼 보여!

2023-10-05 10:13 UTC, shin-mallang commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantImageSuggestionAcceptanceTest.java
> +        List<MultipartFile> 제안된_이미지 = List.of(이미지를_생성한다("images", "이미지1번.wepb"), 이미지를_생성한다("images", "이미지1번.wepb"));
var

2023-10-05 10:13 UTC, shin-mallang commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantImageSuggestionAcceptanceTest.java
> +        이미지_업로드를_설정한다(제안된_이미지);
Ditto

2023-10-05 10:15 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/presentation/ImageController.java
> +    }
이거 어드민으로 가야하는거 아니야?

2023-10-05 10:19 UTC, shin-mallang commented
아 그리고 근본적으로, 이미지 제안이랑 저장을 따르게 보지 말고,
제안에 accept 기능을 넣어서 관리자가 제안을 수정하거나 거절할 수 있도록 하는건 어때?

2023-10-05 12:09 UTC, shin-mallang requested changes

2023-10-05 12:09 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/admin/presentation/AdminController.java
> +    @PostMapping("/images")
레스토랑 이미지 어땡

2023-10-05 12:09 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantImageController.java
> +@RequestMapping("/images")
images들 전부 restaurant-images 로 바꾸는거 어때?

2023-10-05 22:55 UTC, TaeyeonRoyce approved these changes
오도 고생했어!
이미지 로직 쉽지않던데 잘 작성한듯!!

2023-10-05 22:55 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/command/application/RestaurantImageSuggestionService.java
> +        }
요청에 images가 필수인거면 command에서 검증해줘도 괜찮을거 같아

2023-10-05 22:55 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/command/domain/image/RestaurantImageSuggestion.java
> +    private String name;
이거 `imageName` 어때?
`RestaurantImage`에선 image가 명시되어 있어서 name으로만 썼었는데,
`Suggestion`이니깐 image라는걸 명시하면 좋을 것 같아

2023-10-06 11:04 UTC, kdkdhoho approved these changes
어려운 API 잘 구현했네 오도 수고했어 ~~ 👍

2023-10-06 11:04 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantImageAcceptanceTest.java
> +        var 응답 = 이미지_저장_요청을_보낸다(요청);
`이미지_저장_요청`을 따로 만들기보다, `이미지_저장_요청을_보낸다(음식점.id(), "오도", "이미지", "instagram", 이미지)` 가 더 간결하고 이해하기 쉬울 것 같아.

2023-10-06 11:04 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantImageSuggestionAcceptanceTest.java
> +        var 응답 = 이미지_제안_요청을_보낸다(요청, 세션_아이디);
여기도 `이미지_제안_요청을_보낸다(음식점.id(), 제안된_이미지, 세션_아이디)`로 제안합니당

2023-10-11 08:53 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
> +        imageUploadClient.upload(request.images());
근데 다른 것도 그렇고 이 로직이 왜 Service가 아니라 Controller에 있는거야 ??

2023-10-11 12:49 UTC, TaeyeonRoyce commented on backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
> +        imageUploadClient.upload(request.images());
이건 Service에서 이미지 업로드 과정 때문에 Transaction을 오래 잡아서 임시로 분리했어.
파일 이름만 알아도 영속화 하는데 문제는 없어서!

2023-10-12 01:05 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/admin/command/application/AdminServiceTest.java
> +        void 음식점_이미지를_저장한다() {
테스트 이름이 조금 헷갈리는 것 같아.
'이미 저장된 음식점에 사진을 추가한다'는 늬앙스의 이름이 되어야 할 것 같아!

2023-10-12 01:05 UTC, kdkdhoho requested changes

2023-10-12 01:05 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/admin/command/application/AdminServiceTest.java
> +        void 음식점_이미지를_저장한다() {
그리고 이미 저장되어있는 음식점에 사진 추가하는 경우 예외도 잡아야할 것 같아!

2023-10-12 01:10 UTC, kdkdhoho approved these changes

2023-10-24 04:20 UTC, closed without merging