feat: searchbardropdown 컴포넌트 구현
woowacourse-teams/2023-celuveat pull request #56
Opened 2023-07-10 03:14 UTC by turtle601

## 한 일
#34 
#55 

## 구현한 것들
- [ ] SearchbarInput 컴포넌트
- [ ] SearchbarSelectBox 컴포넌트
- [ ] SearchbarDropDown 컴포넌트
- [ ] useSearchbarRef 훅

## 수정한 것들
- [ ] Webpack 파일 resolve 속성 중 오타가 있어서 수정합니다. 자세한 내용은 #55 를 참고해주세요

## 제어 컴포넌트로 리팩토링 하고 싶어요!!
- 비제어와 제어컴포넌트를 공부하면서 이번 DropDown 컴포넌트는 비제어로 구현해봐야지라고 생각해서 비제어로 구현했습니다. 
- 새로 공부한 내용이 많아서 생각보다 엄~청 오래 걸렸네요
- 비제어로 구현하면서 이걸 왜 비제어로 구현해야되지라는 의문이 계속 들었어요... (시간 관계상 일단 비제어 컴포넌트를 만든 상태로 올릴께여!!)

## 그 외 이야기 해보고 싶은 것
- css 스타일 순서 
  - 저희 css 컨벤션 파일을 하나씩 보면서 css를 작성하는 것보다 style-lint를 한 번 사용해보심이 어떠신가요??
- 컴포넌트 스타일 추상화
    - 일단 사용처가 해당 피그마에서 하나밖에 쓰이지 않아서 일단은 스타일 추상화는 하지 않았습니다. 
    - 필요하다면 바로 구현할께여~~     

Close #34 
Close #55

2023-07-10 04:06 UTC, shackstack reviewed
푸만능~ 작성하신 코드 잘 봤습니다.
초반이라 컨벤션 적용을 몇군데 잊으신 것 같아요. 
우선 컨벤션 위주로 피드백 드렸습니다!

2023-07-10 04:06 UTC, shackstack commented on frontend/src/components/@common/Searchbar/SearchbarDropDown.stories.tsx
> +const defaultOptions: Option[] = [
value를 각각 다르게 적용하는 것이 더 용이할 것 같습니다,

2023-07-10 04:06 UTC, shackstack commented on frontend/src/components/@common/Searchbar/SearchbarDropDown.tsx
index.tsx 파일 생성 컨벤션을 잊어먹으셨군요..

2023-07-10 04:14 UTC, D0Dam requested changes
수고하셨어요! 우선 로직보다 styles 나 타입 관련 위주의 리뷰를 먼저 남겼습니다!
대체적으로 정해놓은 스타일(styles/common)을 가져다 써야 할 부분이 많은 것 같아요! 이 부분은 리뷰를 몇몇개만 남겨 놓았으니, 이 공통 스타일을 적용할 수 있는 부분은 적용 부탁드려요!

수정 후 다시 request 부탁드러요!

2023-07-10 04:14 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +  font-size: 1.6rem;
`styles/common` 에 적용해 놓은 상수값으로 작성해 주세요!

```suggestion
  font-size: ${FONT_SIZE.sm}; // 이런식으로
```

2023-07-10 04:14 UTC, D0Dam commented on frontend/src/@types/utils.types.ts
> +}
이 값을 타입으로 따로 지정한 이유가 있을까요?

2023-07-10 04:14 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +      no-repeat 0px 0px;
url 안에 들어갈 값을 추상화해서 외부에서 전달할 수 있게 수정했으면 좋겠어요!

2023-07-10 04:14 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +    height: 3.6rem;
`width` 와 `height` 값은 rem 단위를 피하는 것이 좋아보입니다!

참고 : https://webdesign.tutsplus.com/ko/tutorials/--rem--em-----cms-23984

2023-07-10 04:14 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +    border-radius: 50%;
`%` 가 아닌 `styles/common` 에 있는 상수값을 이용해 주세요!

2023-07-10 04:14 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/index.tsx
> +export default Seachbar;
SearchbarDropDown 파일을 SearchBar 파일로 이름을 변경하거나 SearchbarDropDown 그대로 import 해 주세요!

2023-07-10 04:14 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/SearchbarDropDown.stories.tsx
> +import { Option } from '~/@types/utils.types';
아래와 같이 써 볼까요?

```suggestion
import type { Option } from '~/@types/utils.types';
```

2023-07-10 04:14 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/SearchbarDropDown.tsx
> +  setOptions: ChangeEventHandler<HTMLInputElement>;
`React.ChangeEventHandler<HTMLInputElement>` 와 같이 작성하지 않은 이유가 있을까요?

2023-07-10 11:50 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +const SearchbarTags = styled.ul`
아하... 이런이런... 깜빡해버렸네요 ㅜㅜ 

> 수정했습니다 👍

2023-07-10 12:08 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarDropDown.stories.tsx
> +import { Option } from '~/@types/utils.types';
`import` type을 선언하면 더 좋겠군요!!

2023-07-11 06:07 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +const SearchBarTag = styled.li`
> 수정했습니다 👍

2023-07-11 06:08 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarDropDown.stories.tsx
> +const defaultOptions: Option[] = [
> 스토리북에서 좀 더 다양하게 확인하기 위해서는 다른 값이 더 유용하겠네요!!

2023-07-11 06:16 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +const StyledInputContainer = styled.div`
네이밍에 통일성이 없었던 것 같네요!!

> 수정했습니다 👍

2023-07-11 07:29 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +const SearchbarInput = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(({ onChange }, ref) => (
## HTMLAttribuites<HTMLInputElement> vs InputHTMLAttributes<HTMLInputElement>

__HTMLAttribuites<HTMLInputElement>__
<img width="534" alt="스크린샷 2023-07-11 오후 4 07 13" src="https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/7036b509-9751-4494-b697-c84cbfe03d9f">
HTMLAttributes 는 모든 DOM 요소와 aria요소의 props를 모두 가져와여 그중 InputElement를 찾는 방식입니다. 

---
__InputHTMLAttributes<HTMLInputElement>__
<img width="478" alt="스크린샷 2023-07-11 오후 4 21 58" src="https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/d5385c68-f1f8-4a49-a980-e8decbe385d2">

InputHTMLAttributes<HTMLInputElement>은 HTMLAttribuites<HTMLInputElement>에 input에 필요한 속성이 추가된 타입입니다.

---

### ComponentPropsWithRef<"input">
input 에 필요한 속성에 ref가 추가된 속성 타입입니다. 

추가적으로 아래와 같은 자료들을 참고해서 ComponentPropsWithRef<"input"> 사용하려고 합니다!!

__관련 공부 자료__
[HTMLAttributes 쓰지 마세요!!](https://velog.io/@centraldogma99/HTMLAttributes-HTMLProp-%EC%9D%84-%EC%93%B0%EC%A7%80-%EB%A7%88%EC%84%B8%EC%9A%94)
[ComponentProps관련 자료](https://www.totaltypescript.com/react-component-props-type-helper)

2023-07-11 07:32 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +const SearchbarInput = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(({ onChange }, ref) => (
> `ComponentPropsWithRef<"input">`로 수정했어요!! 👍

2023-07-11 07:34 UTC, turtle601 commented on frontend/src/@types/utils.types.ts
> +}
자동 완성 기능을 실제 앱에서 대충 실행을 해봤었거든요.
그래서 해당 타입을 넣었습니다.
(삭제하겠습니다!!)

2023-07-11 08:10 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +    <StyledSeachIcon src={SearchIcon} alt="search-icon" />
수정 과정에서 prod, dev환경에서는 svg컴포넌트가 인식되지 않아서 #78 이슈를 만들고 해결했습니다!!

> 수정했습니다!! 👍

2023-07-11 09:15 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +  padding: 0 2.6rem 0 2.6rem;
> 수정했습니다 👍

2023-07-11 09:20 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +  font-size: 1.6rem;
> 수정했습니다!! 👍👍

2023-07-11 09:24 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarDropDown.tsx
> +  setOptions: ChangeEventHandler<HTMLInputElement>;
> 수정했습니다!! 👍👍👍

2023-07-11 09:27 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/index.tsx
> +export default Seachbar;
> 수정했습니다 👍👍👍

2023-07-11 09:28 UTC, turtle601 commented on frontend/src/@types/utils.types.ts
> +}
추가적으로 types 폴더 안에 타입 파일 네이밍 규칙도 정하면 좋을 거 같아요!!

2023-07-11 09:31 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +    height: 3.6rem;
> 수정했습니다 👍👍

2023-07-11 13:21 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +  width: 761px;
> 우선 width 를 100% 로 준 다음 이 폭은 상위 부모에게 위임해도 좋을 것 같아요!

위의 방법으로 수정했습니다!! 👍👍👍

2023-07-11 14:25 UTC, shackstack approved these changes

2023-07-12 01:44 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +    border-radius: 50%;
> ProfileImage 컴포넌트를 사용했습니다!! 👍👍

2023-07-12 01:45 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +      no-repeat 0px 0px;
> ProfileImage 컴포넌트를 사용했습니다!! 👍👍

2023-07-12 01:47 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +`;
> 수정했습니다!!

2023-07-12 02:04 UTC, D0Dam commented on frontend/src/@types/utils.types.ts
> +}
제가 생각한 타입을 좀 적어 보겠습니다.

api 명세상 response 정보가 다음과 같습니다.

```
{
"id": 1,
"name": "히밥",
"youtubeChannelName": "@heebab",
"subscriberCount": 1400000,
"profileImageUrl": "http://naver.com"
}
```

필요한 정보는 고유 식별자, 이름, 사진이 될 테니...
```
interface Option {
  id: number;
  name: string;
  profileImageUrl: string;
}
```

정도가 되겠네요.

우선, 이 정도로 간 다음에 나중에 Celeb 이라는 타입을 제대로 만들게 된다면...

```
type celebSearchOption= Pick<Celeb, "id" | "name" | "profileImageUrl">
```

이런 식으로 바꿔서 쓸 것 같아요.

2023-07-12 02:25 UTC, D0Dam requested changes
타입이 좀 바뀌었네요! 만족합니다~!

몇몇 요청사항 리뷰로 달아 놓았습니다! 확인, 수정 후 request 다시 부탁드려요~!

2023-07-12 02:25 UTC, D0Dam commented on frontend/src/@types/celebs.types.ts
> +export type Option = Omit<Celeb, 'subscriberCount'>;
Option 은 너무 추상화가 되었다고... 개인적으로는 그렇게 생각합니다! 
물론 폴더 명에서 Celeb임을 확인할 수 있겠지만,  용도가 검색 창 밑의 select box 에 생기는 option 이라고 한다면, CelebSearchBarOption 정도의 네이밍으로 구체화되면 좋겠다고 생각합니다.
어떻게 생각하시나요?

2023-07-12 02:25 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/SearchbarDropDown.tsx
> +export default SearchbarDropDown;
컨벤션 상 위치가 바뀌어 있습니다!
```suggestion

export default SearchbarDropDown;

const StyledSearchbarDropDown = styled.div`
  div + ul {
    margin-top: 0.7rem;
  }
`;
```

2023-07-12 02:25 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +  width: ${props => `${props.width}px`};
당연히 알수도 있지만 이렇게도 표현해 볼 수 있어요!

```suggestion
  width: ${({width}) => `${width}px`};
```

2023-07-12 02:25 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +}
placeholder의 text 값도 받을 수 있으면 좋을 것 같아요!

2023-07-12 02:25 UTC, D0Dam commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +  padding: 1.1rem 1.1rem;
간단하게 표현해 볼 수 있겠네요~!

```suggestion
  padding: 1.1rem;
```

2023-07-12 04:51 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarDropDown.tsx
> +export default SearchbarDropDown;
> 수정했습니다!!👍👍

2023-07-12 04:51 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +}
> 수정했습니다!!👍👍

2023-07-12 04:51 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +  width: ${props => `${props.width}px`};
> 수정했습니다!!👍👍

2023-07-12 04:51 UTC, turtle601 commented on frontend/src/components/@common/Searchbar/SearchbarSelectBox.tsx
> +  padding: 1.1rem 1.1rem;
> 수정했습니다.👍.👍

2023-07-12 05:12 UTC, shackstack approved these changes

2023-07-12 05:12 UTC, shackstack commented on frontend/.webpack/webpack.common.js
> +        test: /\.(jpg|jpeg|gif|png|ico)?$/,
👍

2023-07-12 05:12 UTC, shackstack commented on frontend/src/components/@common/Searchbar/SearchbarDropDown.tsx
> +function SearchbarDropDown({ options, setOptions, width, placeholder }: SeachbarDropDownProps) {
👍

2023-07-12 05:12 UTC, shackstack commented on frontend/src/components/@common/Searchbar/SearchbarInput.tsx
> +  width: ${({ width }) => `${width}px`};
👍

2023-07-12 05:31 UTC, turtle601 commented on frontend/src/@types/utils.types.ts
> +}
#81 
> 추가적으로 Option 타입 네이밍도 수정했습니다.👍.👍

2023-07-12 05:32 UTC, turtle601 commented on frontend/src/@types/celebs.types.ts
> +export type Option = Omit<Celeb, 'subscriberCount'>;
> 수정했습니다.👍

2023-07-12 05:32 UTC, D0Dam approved these changes

2023-07-12 05:33 UTC, merged