feat: 모바일 지도페이지 뷰 수정
woowacourse-teams/2023-celuveat pull request #587
Opened 2023-10-07 16:06 UTC by shackstack

## ✨ 요약
```
모바일 지도페이지 뷰 개선 및 기타 버그 수정
```

## 1. 모바일 지도 페이지를 개선하였습니다. 

<img width="200" alt="스크린샷 2023-10-07 오전 11 36 19" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/d97f3fb3-275d-4ef5-b567-ba37483fd55e">
<img width="200" alt="스크린샷 2023-10-07 오전 11 36 34" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/31a9d33d-962c-4e40-8b33-5ba7265e8610">
<img width="200" alt="스크린샷 2023-10-07 오전 11 37 10" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/77fcc8c6-9117-4979-bf97-7a4e5819ac2e">

<br><br>

## 😎 해결한 이슈
- close #557

<br><br>

2023-10-09 06:23 UTC, turtle601 requested changes

2023-10-09 06:23 UTC, turtle601 commented on frontend/src/utils/getClickedIcon.ts
> +  const splitPathname = pathname.split('/');
구조 분해 할당을 사용해보는 것은 어떤 가요??

2023-10-09 06:23 UTC, turtle601 commented on frontend/src/utils/getClickedIcon.ts
> +  if (splitPathname[1] === 'signup') return 'user';
해당 코드는 문자열만 바꾸는 코드만 있습니다!! 단순하게 `return splitPathname[1]`을 해도 될 것 같아요!!

기존의 문자열을 사용하는 것이 불편하다면 객체를 사용하면 좀 더 깔끔하고 타입 안정적인 코드를 작성할 수 있을 것 같습니다. 
```tsx
const Map = {
  '': 'home',
  'map': 'map',
  'signup: 'user',
} as const;

export const getClickedIcon = (pathname: keyof Map) => {
  return Map[splitPathname[1]];
}
```

2023-10-09 06:23 UTC, turtle601 commented on frontend/src/router/Root.tsx
> +          {!isMobile && <Footer />}
isMobile 속성을 Footer 내부에 선언해도 되지 않을까

2023-10-10 01:04 UTC, shackstack commented on frontend/src/components/BottomNavBar/BottomNavBar.tsx
> +type BottomIcons = 'home' | 'map' | 'user' | null;
음식점 상세페이지에서는 바텀네브바의 어떤 아이콘도 채워져 있지 않는게 사용자 측면에서 좋을 것 같다는 생각이 들었어요.
특정 링크를 따라 상세페이지로 들어갔을 때를 고려해보면 그때 만약 홈 아이콘이 켜져있다면 사용자가 이 페이지가 홈화면이라고 착각할 수 도 있으니까요.

2023-10-10 01:05 UTC, shackstack commented on frontend/src/pages/RestaurantDetailPage/NearByRestaurantCardList.tsx
> +              <RestaurantCard type="map" restaurant={restaurant} celebs={restaurant.celebs} size="36px" />
이건 예전부터 있던 코드입니다만...

2023-10-10 01:31 UTC, D0Dam approved these changes
제레미~! 잘 만들어주셨네요! 자세한건 모바일 환경에서 해 보아야지 알 것 같아요! 기본적으로 아래 코멘트에 대해서만 확인 부탁드립니다! 수고하셨어요~1

2023-10-10 01:31 UTC, D0Dam commented on frontend/src/components/@common/Map/OverlayMarker.tsx
> +  const [setPreview] = useMapState(state => [state.setPreview]);
이건 그냥 요렇게 써주어도 될 것 같아요~!
```suggestion
  const setPreview = useMapState(state => state.setPreview);
```

2023-10-10 01:31 UTC, D0Dam commented on frontend/src/components/@common/Map/OverlayMarker.tsx
> +    setPreview({ ...restaurant, celebs: [celeb] });
preview에 왜 celebs가 필요하게 되었죠...?
여기에서 celeb 하나를 배열로 주는 구조가 어떻게 나오게 되었는지 들어보고 싶군여..!

2023-10-10 01:36 UTC, shackstack commented on frontend/src/utils/getClickedIcon.ts
> +  const splitPathname = pathname.split('/');
좋습니다

2023-10-10 01:37 UTC, shackstack commented on frontend/src/router/Root.tsx
> +          {!isMobile && <Footer />}
Root 에서 IsMobile로 바텀 네브바, 헤더를 분기처리를 통해 렌더링을 시키는데 Footer만 내부에서 선언할 이유가 있을까요?

2023-10-10 04:56 UTC, turtle601 approved these changes

2023-10-10 04:56 UTC, merged