bug: 모바일에서 음식점 카드 단일 사진으로 변경
woowacourse-teams/2023-celuveat pull request #589
Opened 2023-10-08 03:31 UTC by shackstack

## ✨ 요약
```
모바일에서 음식점 카드 단일 사진으로 변경
```

ImageCarousel 컴포넌트에 disabled 속성을 추가하여 disabled가 true일 시에 캐러셀 동작이 작동하지 않도록 구현하였습니다.
또한 MiniRestaurantCard에 carousel이라는 속성을 추가하였고, carousel이 true인 경우에는 MiniRestaurantCard에 캐러셀이 동작하도록 각 컴포넌트들을 고도화 하였습니다.

<br><br>

<img width="240" alt="스크린샷 2023-10-08 오후 12 26 59" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/6d939a5e-44cb-4d77-93fe-a138c0169d66">
변경전

<img width="240" alt="스크린샷 2023-10-08 오후 12 26 47" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/7ac6e03d-5c44-4d28-877f-d7c88d4ec25f">
변경후

## 😎 해결한 이슈
- close #588 

<br><br>

2023-10-09 06:04 UTC, turtle601 requested changes

2023-10-09 06:04 UTC, turtle601 commented on frontend/src/components/MiniRestaurantCard/MiniRestaurantCard.tsx
> +  carousel = true,
default 값을 false로 하면 컴포넌트에서 사용 시 해당 props를 선언을 안해도 됩니다!!
여럿이서 사용하는 프로젝트인 만큼 boolean 값 같은 경우 default 값을 false로 통일하는 것이 더 좋아 보입니다!!

2023-10-10 01:33 UTC, D0Dam approved these changes
음식점 카드를 좀 전체적으로 통일하고 싶어지네요..ㅠㅜ 우선 해당 PR은 approve 하겠습니다.

2023-10-10 04:56 UTC, turtle601 approved these changes

2023-10-10 05:25 UTC, merged