feat: 음식점의 영상 조회 api 구현
woowacourse-teams/2023-celuveat pull request #61
Opened 2023-07-10 13:13 UTC by shin-mallang

`AcceptanceTest`랑 `CommonAcceptanceSteps` 를 통해서 인수테스트에서 공통적으로 사용할 코드들 정의해뒀어!

close #15, #47

2023-07-10 13:48 UTC, TaeyeonRoyce reviewed
전체적으로 중복이 많이 줄어서 좋은데 한글 변수에 적응하려면 시간이 좀 필요할 것 같네.
짧은 코멘트 남겼고, 고생 많았어~!

2023-07-10 13:48 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/celuveat/acceptance/celeb/CelebAcceptanceSteps.java
> +        return celebs;
Stream으로 쓰는건 어때?

2023-07-10 13:48 UTC, TaeyeonRoyce commented on backend/src/test/java/com/celuveat/celuveat/acceptance/common/CommonAcceptanceSteps.java
> +    }
쓴김에 한글 변수로 통일하는건 어때?

```suggestion
    public static <T> void 값이_존재한다(T 검증값) {
        assertThat(검증값).isNotNull();
    }
```

2023-07-10 14:38 UTC, TaeyeonRoyce approved these changes

2023-07-11 02:14 UTC, kdkdhoho requested changes
테스트 추상화로 인해 앞으로 테스트하기 수월할 것 같아요!
하지만 Video과 관련된 테이블 및 API의 변경에 따라 일부 수정이 필요해 보이는 부분이 있습니다.

고생하셨어요 말랑 😉

2023-07-11 02:14 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/celuveat/video/application/dto/FindAllVideoByRestaurantIdResponse.java
> +) {
Video 조회 API가 변경됨에 따라 필드도 약간 수정이 필요해 보여요 !!

ex) `thumbnail` 추가, `publishedDate` -> `uploadDate`

2023-07-11 02:14 UTC, kdkdhoho commented on backend/src/main/java/com/celuveat/celuveat/video/infra/persistence/VideoQueryDao.java
> +                    c.name as celeb_name
이 부분 또한 테이블 변경에 따라 약간 달라져야할 것 같아요.

2023-07-11 02:14 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/celuveat/acceptance/common/CommonAcceptanceSteps.java
> +    }
이 static 메서드는 어떤 용도인가요?

2023-07-11 02:14 UTC, kdkdhoho commented on backend/src/test/java/com/celuveat/celuveat/acceptance/common/CommonAcceptanceSteps.java
> +    }
자주 쓰일만한 검증을 빼서 너무 편하게 사용할 것 같아요 👍

2023-07-11 02:18 UTC, shin-mallang commented on backend/src/main/java/com/celuveat/celuveat/video/application/dto/FindAllVideoByRestaurantIdResponse.java
> +) {
다음 PR 적용 예정!

2023-07-11 02:19 UTC, shin-mallang commented on backend/src/test/java/com/celuveat/celuveat/acceptance/common/CommonAcceptanceSteps.java
> +    }
log().all()이랑
APPLICATION_JSON 세팅 과정 간소화!

2023-07-11 02:20 UTC, kdkdhoho approved these changes
굿 👍

2023-07-11 02:22 UTC, merged