refactor: 음식점 상세페이지 usequeries 처리
woowacourse-teams/2023-celuveat pull request #649
Opened 2023-11-08 01:51 UTC by shackstack

## ✨ 요약
``` 
음식점 상세페이지에 useQueries 처리 및 관심사 분리를 통해 waterfall로 인한 로딩 지연 문제를 해결하였습니다.
```

<br><br>

## 😎 해결한 이슈
- close #648 

<br><br>

2023-11-13 05:16 UTC, turtle601 requested changes
고생하셨습니다. 이런 디테일도 챙기다니, 굳굳!!

어떤 요청에서 워터풀 현상이 일어났고 이를 어떻게 개선했는지 좀 더 자세한 설명이 있었으면 좋겠어요!!

useQueries를 사용한 것 외에 코드 수정사항이 있던데 이는 왜 바꿨는지도 설명해주시면 감사하겠습니다.

2023-11-13 05:16 UTC, turtle601 commented on frontend/src/pages/RestaurantDetailPage/RestaurantDetail.tsx
> +          <RestaurantDetailLikeButton showText={false} restaurantId={restaurantId} celebId={celebId} />
props를 늘린 이유가 뭔가요??

2023-11-13 05:16 UTC, turtle601 commented on frontend/src/pages/RestaurantDetailPage/ImageViewer.tsx
> +function ImageViewer({ restaurantId, celebId }: ImageViewerProps) {
이것도 props를 수정한 이유가 무엇인가요?

2023-11-14 00:59 UTC, shackstack commented on frontend/src/pages/RestaurantDetailPage/ImageViewer.tsx
> +function ImageViewer({ restaurantId, celebId }: ImageViewerProps) {
이전에는 상위 컴포넌트에서 images를 fetch해서 ImageViewer에 props로 전달하는 구조였습니다.
어떤 컴포넌트는 비즈니스로직을 해당 컴포넌트애서 처리하는 반면 ImageViewer의 경우에는 상위 컴포넌트에서 비즈니스 로직을 처리하니까 통일성이 저해되어 통일성을 주기위해 이렇게 처리하였습니다.

2023-11-14 00:59 UTC, shackstack commented on frontend/src/pages/RestaurantDetailPage/RestaurantDetail.tsx
> +          <RestaurantDetailLikeButton showText={false} restaurantId={restaurantId} celebId={celebId} />
부모컴포넌트로부터 레스토랑 데이터를 props로 받아오던 구조는 부모컴포넌트의 fetch가 만료되기전까지 다른 자식컴포넌트가 비동기요청을 수행하지못하는 waterfall 문제를 낳게되었습니다.
그래서 자식컴포넌트에서 fetch를 수행하도록 수정하면서 waterfall를 개선함과 동시에 관심사 분리를 하고자 하였습니다.

2023-11-17 02:27 UTC, shackstack commented
> 어떤 요청에서 워터풀 현상이 일어났고 이를 어떻게 개선했는지 좀 더 자세한 설명이 있었으면 좋겠어요!!

https://github.com/woowacourse-teams/2023-celuveat/issues/648 참고해주세요! 

추가적으로 부모와 자식컴포넌트에서 useQuery로 비동기요청을 보내는 경우 부모컴포넌트에서 비동기 요청이 다 마쳐야지 자식컴포넌트의 비동기요청이 수행이 되더라구요. 
그래서 부모컴포넌트에서 수행되던 비즈니스로직을 자식컴포넌트에 적절하게 관심사분리를 진행하였고 자식컴포넌트에서 여러 useQuery가 사용되는 경우 useQueries를 통해 병렬적으로 처리되도록하였습니다.

2023-11-20 06:52 UTC, turtle601 approved these changes
요구사항 잘 반영해주셨군요!!!

2023-11-20 06:54 UTC, D0Dam approved these changes

2023-11-20 06:56 UTC, merged