feat: 셀럽 베너 컴포넌트 구현
woowacourse-teams/2023-celuveat pull request #68
Opened 2023-07-11 04:31 UTC by D0Dam

### 셀럽 배너 컴포넌트 예시는 아래와 같습니다.

<img width="1787" alt="스크린샷 2023-07-11 오후 1 26 18" src="https://github.com/woowacourse-teams/2023-celuveat/assets/51052049/b7e4aa49-403a-4a3d-a4b7-2e3175ef7336">

2023-07-11 06:02 UTC, shackstack approved these changes

2023-07-11 06:02 UTC, shackstack commented on frontend/src/components/CelebBanner/CelebBanner.tsx
> +        `};
👍

2023-07-11 06:02 UTC, shackstack commented on frontend/src/components/CelebBanner/CelebBanner.stories.tsx
> +  },
backgroundImageUrl가 있는 버전도 하나 있으면 좋을 것 같아요.

2023-07-11 06:14 UTC, D0Dam commented on frontend/src/components/CelebBanner/CelebBanner.stories.tsx
> +  },
케이스 하나 추가해 놓겠습니다~!

2023-07-12 01:38 UTC, turtle601 requested changes
타입 컨벤션 관련 논의드리고 싶은 내용을 작성했습니다. 논의 후 approve 드릴께여~~

2023-07-12 01:38 UTC, turtle601 commented on frontend/src/components/CelebBanner/CelebBanner.tsx
> +interface CelebBannerProps {
해당 props의 경우 저의 API 명세서 GET "/celebs/{id}"와 유사한 프로퍼티가 많네요!!

@types 폴더에 api 타입을 선언하고 해당 props 타입에는 api 타입을 뽑아서 쓰는 식으로 하는 방법에 대해서는 어떻게 생각하시나요??

__예시코드__
```ts
// @types/celeb.types.ts

interface CelebAPI {
    "id": number;
    "name": string;
    "youtubeChannelName": string;
    "subscriberCount": number;
    "youtubeChannelUrl": string;
    "backgroundImageUrl": string | null;
    "profileImageUrl": string,
    "restaurantCount": number
}

// src/components/CelebBanner/CelebBanner.tsx
type CelebBannerProps = Omit<CelebAPI, "id">
```

2023-07-12 01:38 UTC, turtle601 commented on frontend/src/components/CelebBanner/CelebBanner.tsx
> +interface CelebBannerProps {
컨벤션? 적인 논의가 더 필요해 보여요!!

2023-07-12 04:03 UTC, turtle601 approved these changes
#81 관련 논의가 끝나서 approve 하겠습니다~~

2023-07-12 04:57 UTC, D0Dam commented on frontend/src/components/CelebBanner/CelebBanner.tsx
> +interface CelebBannerProps {
나중에 Celeb 타입이 생기면 그걸로 대체해 보겠습니다~!

2023-07-12 04:58 UTC, merged