feat: 지도 컴포넌트 구현
woowacourse-teams/2023-celuveat pull request #71
Opened 2023-07-11 05:53 UTC by shackstack

- 마커 하나
<img width="528" alt="스크린샷 2023-07-11 오후 2 52 58" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/50519a44-eaa3-411d-a95c-171feb967514">

- 마커 여러개
<img width="1029" alt="스크린샷 2023-07-11 오후 2 52 30" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/f2bac564-4512-4e50-9131-9a67f388be9a">

2023-07-11 07:12 UTC, D0Dam reviewed
map 수고하셨습니다!!
궁금한 점들을 남겨두었습니다. 리뷰 코멘트 확인해주세요~!

2023-07-11 07:12 UTC, D0Dam commented on frontend/.webpack/webpack.common.js
> +const InterpolateHtmlPlugin = require('interpolate-html-plugin');
이건 왜 추가된건가요??

2023-07-11 07:12 UTC, D0Dam commented on frontend/.webpack/webpack.common.js
> +    }),
요것두!
약간 환경변수 관련 로직이라면 따로 PR 날리고 머지시킨다음에 진행하는게 좋을 것 같은데요?
kakaomap에 의해 강제되는 로직이면... 별 수 없겠지만요..

2023-07-11 07:12 UTC, D0Dam commented on frontend/src/@types/global.d.ts
> +}
Window interface를 declare 파일에 선언한 이유가 있나요?

2023-07-11 07:12 UTC, D0Dam commented on frontend/src/components/@common/Map/Map.tsx
> +}
위도 경도는 0~180까지의 범위가 있어요!
이 범위 안의 정수, 소수값이 들어올 수 있게 타입을 구체화하면 더 좋을 것 같아요!

2023-07-11 07:12 UTC, D0Dam commented on frontend/src/components/@common/Map/Map.tsx
> +  level: number;
어느 때 쓰이는 props인지 간단히 설명해주실 수 있나요?

2023-07-11 07:12 UTC, D0Dam commented on frontend/yarn.lock
> +dotenv@^16.0.0, dotenv@^16.3.1:
전의 lock 파일과 왜 버전이 달라지는거죠?
노드 버전 v18.16.1에 맞는 dotenv 버전은 어떤 건가요?

2023-07-11 08:21 UTC, shackstack commented on frontend/.webpack/webpack.common.js
> +const InterpolateHtmlPlugin = require('interpolate-html-plugin');
우선 dotenv는 process.env로 환경변수를 사용하기 위해 설치하였고,
아래 InterpolateHtmlPlugin는 html파일에서 환경변수에 접근하기 위해 설치하였습니다.

2023-07-11 08:21 UTC, shackstack commented on frontend/.webpack/webpack.common.js
> +    }),
그래서 따로 이슈를 파서 해당 이슈번호로 커밋을 생성하였습니다. 괜찮을까요?

2023-07-11 08:21 UTC, shackstack commented on frontend/src/@types/global.d.ts
> +}
window라는 네이밍이 전역으로 선언해야할 것 같아서 해달 파일에 선언하였는데 다시보니 적절치 않았던 것 같네요.
타입관련 컨벤션을 정한 뒤에 옮기도록 할게요.

2023-07-11 08:21 UTC, shackstack commented on frontend/yarn.lock
> +dotenv@^16.0.0, dotenv@^16.3.1:
노드버전 12이상이면 상관없습니다.

2023-07-12 02:03 UTC, turtle601 commented on frontend/src/@types/global.d.ts
> +}
#81

2023-07-12 02:19 UTC, turtle601 requested changes

2023-07-12 02:19 UTC, turtle601 commented on frontend/.storybook/main.ts
> +    '<script
이걸 쓰기 위해서 webpack의 `InterpolateHtmlPlugin` 속성을 사용하신 건가요??

2023-07-12 02:19 UTC, turtle601 commented on frontend/.webpack/webpack.common.js
> +      'process.env': JSON.stringify(process.env),
```js
   new webpack.DefinePlugin({
      CUSTOM_VAR: JSON.stringify(process.env.CUSTOM_VAR),
      CUSTOM_VAR2: JSON.stringify(process.env.CUSTOM_VAR2),
    }),
```

이런 식으로 해당 env값을 세분화하는 것은 어떤가요??

2023-07-12 02:19 UTC, turtle601 commented on frontend/src/components/@common/Map/Map.stories.tsx
> +    width: '1000px',
#81

2023-07-12 02:19 UTC, turtle601 commented on frontend/src/components/@common/Map/Map.tsx
> +  useEffect(() => {
커스텀 훅이나 util함수로 빼서 관리해도 좋은거 같아요!!

2023-07-12 02:35 UTC, D0Dam approved these changes

2023-07-12 05:40 UTC, shackstack commented on frontend/.storybook/main.ts
> +    '<script
아니요 InterpolateHtmlPlugin는 index.html파일에서 %환경변수% 형태로 환경변수를 사용하기 위함입니다.

2023-07-12 05:40 UTC, shackstack commented on frontend/.webpack/webpack.common.js
> +      'process.env': JSON.stringify(process.env),
위 코드는 전역변수 process.env에 process.env 값을 할당하는 것입니다. 
제안해주신 코드로 사용하게 되면 환경변수를 생성할 때 마다 웹팩에 접근하여 `CUSTOM_VAR~`형식으로 전역변수를 설정해 줘야하는데 어떤 효용이 있는지 잘 모르겠습니다.

혹여나 'process.env'라는 네이밍의 문제가 있다고 생각하시면 함께 의논해 보면 좋을 것 같아요.

2023-07-12 08:10 UTC, turtle601 commented on frontend/.webpack/webpack.common.js
> +      'process.env': JSON.stringify(process.env),
좋아여~~

2023-07-12 08:16 UTC, shackstack commented on frontend/src/components/@common/Map/Map.tsx
> +  useEffect(() => {
커스텀 훅으로 분리해서 사용할 예시들이 잘 안 떠올라서요. 
그런 예상되는 예시들이 떠오르면 그때가서 분리해도 늦지 않을 것 같아요.

2023-07-12 08:28 UTC, turtle601 approved these changes
변경사항 잘 확인했습니다~~ approve 하겠습니다!!

2023-07-12 08:28 UTC, merged