feat: RestaurantDetailInfo 컴포넌트 구현
woowacourse-teams/2023-celuveat pull request #77
Opened 2023-07-11 07:55 UTC by shackstack

<img width="1490" alt="스크린샷 2023-07-11 오후 4 54 25" src="https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/1a6f7a9d-ae21-4e3c-b1e0-2c4f30889063">

## Todo

- [x] UI 구현
- [x] 주소 및 전화번호 복사 기능 구현

2023-07-12 06:01 UTC, D0Dam requested changes
수고하셨습니다~! 리뷰 남겨놓았으니 확인, 수정 부탁드려요!
완료되면 다시 request 부탁드립니다!

2023-07-12 08:22 UTC, D0Dam commented on frontend/src/utils/getFilteredReviewCount.ts
> +};
그럴 수 있겠네요..! 개인적으로는 좀 더 추상화단계를 높이고 싶긴 하지만, 나중에 더 사용처가 증가한다고 하면 그 때 가서 해봐도 좋은 경험이 될 것 같아요!
의견 감사합니다~!

2023-07-13 00:33 UTC, turtle601 requested changes

2023-07-13 00:33 UTC, turtle601 commented on frontend/src/@types/global.d.ts
> +  const content: (props: SVGProps<SVGElement>) => ReactElement;
???!! 이전 코드랑 무슨 차이가 있는거죠???

2023-07-13 00:33 UTC, turtle601 commented on frontend/src/components/RestaurantDetailInfo/RestaurantDetailInfo.tsx
> +            <StyledReviewCount>({getFilteredReviewCount(reviewCount)})</StyledReviewCount>
`getFilteredReviewCount`의 미친 재활용성 미쳤다...!!

2023-07-13 00:33 UTC, turtle601 commented on frontend/src/components/RestaurantDetailInfo/RestaurantDetailInfo.tsx
> +  padding: 8px 12px;
저희 padding, margin도 rem 단위로 하기로 컨벤션을 정했으니 수정해주세여~~

2023-07-13 00:33 UTC, turtle601 commented on frontend/src/components/RestaurantDetailInfo/RestaurantDetailInfo.tsx
> +  height: fit-content;
최근 `height : fit-content`에 대해 공부하다가 알게된 사실....
확인 부탁드립니다!!

👍👍

[height:fit-content사용법](https://digndig.kr/css/2021/08/27/Css_heightFitcontens.html)

2023-07-13 04:04 UTC, shackstack commented on frontend/src/@types/global.d.ts
> +  const content: (props: SVGProps<SVGElement>) => ReactElement;
이전 코드의 경우 ReactComponent로 svg파일을 사용할 때의 타입 설정이고 
현재 코드의 경우에는 ReactElement로 svg파일을 사용할 때의 타입 설정입니다.

2023-07-13 04:04 UTC, shackstack commented on frontend/src/components/RestaurantDetailInfo/RestaurantDetailInfo.tsx
> +  height: fit-content;
추가적인 2개의 속성이 왜 필요한지는 안적혀있는데 왜인지 알려주실 수 있나요?

2023-07-13 05:41 UTC, D0Dam approved these changes
수고하셨습니다~! 아래 리뷰만 마저 확인해주세요~! approve 할게요~!

2023-07-13 05:41 UTC, D0Dam commented on frontend/package.json
> +    "@storybook/react": "^7.0.25",
이 친구도 dependencies 에서 없애줄까요?

2023-07-18 06:07 UTC, closed without merging