chore: msw 초기환경 세팅
woowacourse-teams/2023-celuveat pull request #92
Opened 2023-07-12 06:49 UTC by shackstack

## ✨ 요약
```
msw 환경 설정
```

<br><br>

## 😎 해결한 이슈
- close #88 

<br><br>

2023-07-12 07:17 UTC, turtle601 requested changes
msw 셋팅 굳굳 ~~ 베리 나이스~~

2023-07-12 07:17 UTC, turtle601 commented on frontend/src/mocks/handlers.ts
요건 테스트 파일인가용??

2023-07-12 08:08 UTC, shackstack commented on frontend/src/mocks/handlers.ts
msw에 있는 예시코드입니다. handler 작성할 때 한번 훓고 시작하시면 좋을 것 같아서..ㅎ

2023-07-13 00:35 UTC, turtle601 approved these changes
msw 셋팅 모두 확인했습니다. approve(합격 목걸이) 드리겠습니다 👏👏👏

2023-07-13 05:37 UTC, D0Dam requested changes
msw 도입~! 여기에서 추가적으로 dev 환경에서만 msw 가 작동하도록 설정해주실 수 있을까요?

2023-07-13 05:37 UTC, D0Dam commented on frontend/src/mocks/browser.ts
> +x;
요건 뭔가요..?

2023-07-13 05:37 UTC, D0Dam commented on frontend/src/mocks/browser.ts
> +export const worker = setupWorker(...handlers);
여기 있는 주석은 지워주면 좋을 것 같아요!

2023-07-13 06:03 UTC, turtle601 approved these changes

2023-07-13 06:04 UTC, D0Dam approved these changes
만나서 같이 고친걸로 질문에 대한 답변 대신하고 approve 하겠습니다~!

2023-07-13 06:04 UTC, merged